### ISSUE TITLE
Ctrl-D and Ctrl-U functionality

### ISSUE THREAD

**Issue by paavanb** [vrapper/vrapper#104]
In Vim, `<C-D>` and `<C-U>` scroll only half a page so it's easy to keep your place. I've noticed that vrapper instead scrolls a full page, which makes it a bit more difficult to scroll through a document. Would it be possible to fix this?

My current hack is the following two remaps:

```
noremap <C-d> MztM
noremap <C-u> MzbM
```

The caveat to this hack though is that the cursor doesn't retain its absolute position on the page as in vim, and instead resets to the middle. It's not bothering me too much though.

**Comment by brauliobo** [comment]
I really miss those two shortcuts, PageDown and PageUp are pretty bad to use. The @pbhavsar hack didn't work here.

**Comment by keforbes** [comment]
@brauliobo, this feature was implemented three years ago (see my previous comment), you don't need to use that hack.  All you need to do is unbind `Ctrl+D` and `Ctrl+U` from Eclipse's settings.  Vrapper only receives key presses which Eclipse does not have a binding for and by default, Eclipse has those keys mapped to other operations.

**Comment by brauliobo** [comment]
ok @keforbes, thanks for answering :)
