### ISSUE TITLE
mapping jj to <Esc> does not work on mac osx

### ISSUE THREAD

**Issue by nilsbecker** [vrapper/vrapper#150]
the mapping is picked up from ~/.vrapperrc but upon hitting jj, a j is inserted before the insert mode is left and remains in the text.

eclipse 3.7 (classic version of juno)
mac os x 10.7

**Comment by vinay-keshava** [comment]
after creating the _vrapperrc script how to tell vrapper thats the config file ?

**Comment by keforbes** [comment]
> after creating the _vrapperrc script how to tell vrapper thats the config file ? 
> automatically detects the config file?

Yes, it automatically detects the file.

If the file is _not_ found, you'd see a message like this in the eclipse log:
```
!MESSAGE No .vrapperrc or _vrapperrc found.
```
