### ISSUE TITLE
integrate into package explorer, etc?

### ISSUE THREAD

**Issue by nhajratw** [vrapper/vrapper#173]
Maybe a longshot, but is there any way to integrate vrapper so we can use vim navigation in other views like package explorer, problems, search, etc?

**Comment by albertdev** [comment]
We now have something for this in our Unstable Update Site after #820 got merged.

Go to the Keyboard shortcuts section in Preferences and search for "Arrow Map" (the screenshot below shows slightly more so ignore the other things):

![issue_108_config_defaultscheme](https://user-images.githubusercontent.com/1451362/50428730-23daec80-08ba-11e9-9fe9-2171d2009b12.PNG)

Now select the "Vrapper Down Arrow Map" shortcut and click in the "Binding" text field, then use it to replace `F15, J` by `J` (or whatever key you want). Repeat for the other 3 shortcuts.

Alternatively you can select "Vim's key bindings" from the Scheme dropdown at the top, but that introduces Vim keybindings for everything (you might want to export your settings before choosing that or you could loose your finely-honed set of key bindings).

Anyway, once you click Apply and close the Preferences dialog you can now use those keys to navigate through the package explorer. It emulates the arrow keys, so <kbd>H</kbd> and <kbd>L</kbd> can be used to open / close the `+` nodes in trees, then <kbd>J</kbd> and <kbd>K</kbd> can be used to step in them.

Let us know what you think, at least if you are still using Eclipse at this point.
