### ISSUE TITLE
implement `gn` text object

### ISSUE THREAD

**Issue by justinmk** [vrapper/vrapper#291]
I don't know how difficult this would be to implement, so I'm just putting it out there. Vrapper is already amazing, and makes Eclipse actually fun to use. 

Vim 7.3.610 added the `gn` text object, which selects the `/` register (ie, the last search result). So you can combine this with `c` and make some arbitrary changes, and then use `.` to repeat those changes to each search result. (Arguably, this obviates the need for a "multiple cursor" gimmick.)

See here for a use case and explanation by the Vim contributor:

http://www.reddit.com/r/vim/comments/1ket9u/replacing_word_on_nth_consecutive_lines/

**Comment by albertdev** [comment]
Small update: I got the normal mode stuff going, both `gn` as well as `dgn` appear to work.

The visual mode behavior is a little bit harder to get working though, especially when going backwards. I might need to fix #539 while I'm at it, but I haven't really analyzed it completely.

**Comment by albertdev** [comment]
Ok, while it took 1.*something* years to implement, this feature is now a part of Vrapper. I hope that @justinmk is still using Eclipse... ;-)

This feature will be included in the next release or unstable build, whichever comes first. I've tried to crosscheck with Vim to make sure I got it right, but do give feedback in case I missed something.

**Comment by justinmk** [comment]
I still use eclipse. thanks!

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.51.20150127) which includes this fix.  Give it a try and let us know if you run into any issues.  Thanks!

**Comment by loonies** [comment]
Awesome feature.
