### ISSUE TITLE
Command line mode breaks upon change of package

### ISSUE THREAD

**Issue by ghost** [vrapper/vrapper#303]
After you drag a class from one package to another, trying to enter in command mode results only in a message(status) showing that you are in command line mode but no actual bar shows. I tried entering a command, hoping that the bar is only invisible, but that didn't work. Command mode broke for all the classes than had been in the destination package at the time of the move but not for classes created in the destination package afterwards. It didn't brake for any of the classes in the source package.

**Comment by albertdev** [comment]
This issue hasn't been updated for over a year, and since then we were able to fix #375 and #567.

I'm going to close this issue with the hope that those other fixes made this (somewhat similar) problem go away.
