### ISSUE TITLE
VI-like control of the content-assist menu

### ISSUE THREAD

**Issue by brandonwillard** [vrapper/vrapper#332]
It would be great if one could cycle through the content assist menu with 'hjkl' motions, perhaps even close it with <C+C>.  Basically, after pressing <C+Space>, the menu could be controlled in a VI way, without resorting to ESC or the direction arrows.

**Comment by gustavklopp** [comment]
I was looking for that for a while, thanks @keforbes ! That's a wonderful trick!
How about putting that into the doc? http://vrapper.sourceforge.net/documentation/?topic=commands

**Comment by keforbes** [comment]
Sorry, it's in the Configuration part of the docs since it's a boolean setting to enable/disable rather than a command to execute.
http://vrapper.sourceforge.net/documentation/?topic=configuration#vrapper
