### ISSUE TITLE
Variant of :find for Open Resource

### ISSUE THREAD

**Issue by Konfekt** [vrapper/vrapper#413]
How about a command to open the Open Resource GUI. It resembles a Fuzzy finder such as Ctrl+P (where it could be mapped to in normal mode) and would be a convenient addition to :find.

**Comment by tecfu** [comment]
I think this is the list of commands we are all looking for: https://github.com/pellaton/eclipse-cheatsheet/blob/master/eclipse4.9/shortcut-export-eclipse-win-4.9-sorted.csv
