### ISSUE TITLE
insert mode mappings reversed before or after an autocompleted delimiter

### ISSUE THREAD

**Issue by Konfekt** [vrapper/vrapper#422]
If bracket autocompletion is enabled, the following happens.
Let ```inoremap ;c \chi```. Then, with * indicating cursor position, typing ```;c``` in
```
(*)
```
yields
```
(ihc\)
```
This occurs for TeXLipse, but maybe also for other autocompletion implementations?

**Comment by albertdev** [comment]
I finally found the problem. Eclipse did move the caret back in some cases depending on whether completion mode was active, but I used the workaround from another bit of code whereby I register a "position listener". This reversal problem should hence not happen any more.

**Comment by Konfekt** [comment]
Wow! Thanks Albert.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.61.20151115) which includes this fix.  Good job @albertdev for finding a solution to this!
