### ISSUE TITLE
c-u and c-d offset with linewrapping

### ISSUE THREAD

**Issue by Konfekt** [vrapper/vrapper#426]
This might be a curiosity as eclipse does officially not support line wrapping if I am not mistaken though is http://dev.cdhq.de/eclipse/word-wrap/. But if enabled, scroll commands such as ```<c-u>``` and ```<c-d>``` introduce slight offsets by one or two lines. That is ```<c-u><c-d>``` does not return to its initial position even if neither of these commands hit the end of the file.

**Comment by albertdev** [comment]
It looks like some people are finally working on getting this done in Eclipse itself:

https://git.eclipse.org/r/#/c/33542/
https://git.eclipse.org/r/#/c/21478/

I don't know how Vrapper will behave with those changes but I'm closing this issue for now.

**Comment by Konfekt** [comment]
Thanks for the update!
