### ISSUE TITLE
Recording of macros aborts on carriage return (and ignores autocompleted code)

### ISSUE THREAD

**Issue by cinocode** [vrapper/vrapper#437]
I'm running Vrapper 0.42.0 in Eclipse 4.3.2 on Windows 7.

If I try to record a macro (editing a .java file) over multiple lines, the recording aborts as soon as I enter a carriage return. This can be avoided by pressing `<esc>o` instead.
Also any code that is autocompleted by eclipse will not be contained in the macro.

Reproduction while editing a java file:
```
    qqo
    1<cr>
    2<cr>
    3<cr>
    q
    @q
```
This will only print the 1.

**Comment by keforbes** [comment]
I'm closing this issue.  I was never able to reproduce it and it's almost 2 years old now.
