### ISSUE TITLE
inoremap \ ;

### ISSUE THREAD

**Issue by Konfekt** [vrapper/vrapper#450]
Over here, if the line ```inoremap \ ;``` is in .vrapperrc, then typing ```\``` in insert mode yields ```\```, typing ```\``` again yields ```;```. The backslash now alternates between backslash and semicolon. 

Expected: only ```;``` appears when typing ```\```.

**Comment by keforbes** [comment]
I'm closing this issue.  It was opened two years ago and I believe it was just a consequence of the content assist getting in the way when using TeXlipse.
