### ISSUE TITLE
Add support for ':buffer#' command

### ISSUE THREAD

**Issue by loonies** [vrapper/vrapper#468]
Switches between last two buffers (tabs in this case).

**Comment by albertdev** [comment]
This issue has been assigned to me for a couple of weeks now so I thought it's time for an update.

I've got `:buffers` completely implemented. Everything related to bufferswitching works for simple editors (java, text, c, ...). As soon as you try with xml, html or any other editor with multiple pages, the alternate buffer recognition goes out the window, and it even affects `:buffer <n>`.

TL;DR: it might take another week / few weeks or so to get it done.

**Comment by albertdev** [comment]
Ok, turns out it took about a month and 3 rewrites but you should now be able to press `CTRL-^` as well as `:b#` to switch buffers!

However, whilst I was at it I actually reimplemented the `:buffers` command to list Vrapper buffers, so using ids is now also possible.

You can try it out once @keforbes pushes a build to the unstable update site.

**Comment by albertdev** [comment]
I've been doing some more testing but I don't quite like the current behaviour... For some reason, switching back to an XML view will reset the cursor position.

I will need to find a fix for that, who knows what it might do in other editors...

**Comment by albertdev** [comment]
Ok, I said it before that it would take some hackery and my latest commit proves it. However, in my opinion the current code should handle most use-cases now.

**Comment by albertdev** [comment]
@keforbes has updated the unstable site with a new build (0.51.20150127). Give it a try and let us know if you happen to run into any issues. Thanks!

**Comment by loonies** [comment]
@albertdev this looks awesome, thanks!

Somehow I missed Github notifications.
