### ISSUE TITLE
Vrapper Indent & Eclipse Settings | Eclipseaction & visual mode

### ISSUE THREAD

**Issue by AlexJF** [vrapper/vrapper#471]
So from what I gathered, Vrapper uses its own indentation mechanism using uniquely the settings defined in the .vraperrc.

However, I work on several projects with different styles and so I am not able to keep Vrapper and Eclipse constantly on sync (custom styles on per-project settings).

In https://github.com/vrapper/vrapper/issues/445, a mechanism is described to associate the use of the native eclipse shifting with <</>> putting the following in .vrapperrc:

```
eclipseaction shiftLeft org.eclipse.ui.edit.text.shiftLeft
eclipseaction shiftRight org.eclipse.ui.edit.text.shiftRight
map < :shiftLeft<enter>
map > :shiftRight<enter>
```

This almost addresses the issue. However, as also pointed out in that issue, the execution of shiftLeft or shiftRight appears to change the mode back to normal. While this is fine for mouse selections with `:set novirtualmouse`, it clears selections in visual mode preventing multiple consecutive indentations.

So I would appreciate if Vrapper did one of the following:
- Sync Vrapper indentation settings with Eclipse indentation (including per-project overrides).
- Do not revert back to normal mode after executing one of those eclipse actions.

The second approach seems easier to implement. Not sure if some functionality of Vrapper actually depends on this change to normal mode to work. If that is the case perhaps a `eclipsevisualaction` command could be added for this specific case?

**Comment by spattersongt** [comment]
If I use Alex's solution, my indention works perfectly but repeating the command with . does not.  For example, selecting text, indent, repeat, repeat

Vjjjj>..

Indents once but should indent 3 times. 

Vjjjj>>>

works however, so it's not a big deal
