### ISSUE TITLE
Pressing comma in parameter list does not move to next parameter

### ISSUE THREAD

**Issue by 372046933** [vrapper/vrapper#472]
The problem seems to be specific to Eclipse Luna.
![a2](https://cloud.githubusercontent.com/assets/1251167/3548935/33c076c6-08bd-11e4-94fc-50ac11f32fac.png)

**Comment by muellan** [comment]
Works fine for me. Windows 8.1, 32Bit Eclipse (CDT, Vrapper) buildId=4.4.2.M20150204-1700

**Comment by albertdev** [comment]
@372046933
We haven't heard back from you so I'm going to close this issue. Please reopen if you still think this is a bug and have any further info.

**Comment by 372046933** [comment]
@keforbes Thank you! And it is OK now on Luna Service Release 1
