### ISSUE TITLE
i_CTRL_Y (Insert the character which is above the cursor) duplicates some characters

### ISSUE THREAD

**Issue by haridsv** [vrapper/vrapper#477]
I had this line:

      private static boolean createOverwrites = false;

and I opened a new line below it and used `^Y` to copy the characters from the prior line, then I ended up with the below line:

      privvate staatic booolean createOverwrites = faalse;

The characters "v", "a", "o" and "a" (characters at positions 4, 11, 17/18 and 44) have duplicates. I tried it on a few other lines and I couldn't reproduce it. I also tried the above problem line with different indentation and in different locations in the file, and was able to reproduce the issue consistently. However it seems to be related to syntactic context, as the same line if put in quotes doesn't reproduce the problem, e.g., the below:

      "private static boolean createOverwrites = false;"

**Comment by keforbes** [comment]
I'm closing this issue.  It has been sitting idle for almost two years and I was never able to reproduce it.
