### ISSUE TITLE
Indent a line with == moves the cursor to the next line

### ISSUE THREAD

**Issue by richq** [vrapper/vrapper#484]
Pressing `==` indents the current line but moves the cursor to the next line. The cursor should remain on the same line and in the same position (or go to end of the line if that's not possible, i.e. the new indentation makes the line shorter in total than the old cursor position). I think staying on the same line at least would be a good compromise if the same position is impossible.

I only noticed this after updating to 0.46 and thought it might be a new difference to Vim, but I've checked back to version 0.42 and it always seems to have been this way (earlier than that the mapping was not available).

**Comment by solde9** [comment]
@albertdev 's fix for #608 fixed this too.

**Comment by keforbes** [comment]
@solde9 is right, I can't reproduce this anymore with the latest build (after some very basic testing).  I'll go ahead and close the defect.  Feel free to re-open it if you find steps which still reproduce the issue.
