### ISSUE TITLE
Jump movement commands don't add to Eclipse's navigation history.

### ISSUE THREAD

**Issue by MrPay** [vrapper/vrapper#487]
There are a number of VIM movement commands that cause cursor jumps but that don't add  to Eclipse's navigation history, some examples: <code>[{ ]} / n N gg</code>. But in VIM, these commands add to the jump list navigable with <code>&lt;C-O&gt; &lt;C-I&gt;</code>.

**Comment by muellan** [comment]
+1 "me too!"

**Comment by albertdev** [comment]
I have been doing some experiments but it doesn't seem to work quite right. Is it okay that `''` actually adds to the history every time you use it? It seems Vim keeps a real MRU (most recently used) stack whereas Eclipse simply has a linear list with previous locations for which only the most recent duplicates get filtered.

I'll see if I have some time to work on this tomorrow though my machine needs urgent maintenance...

**Comment by albertdev** [comment]
Ok, I think it is stable enough to push it but it does have the following remarks:

* Vrapper jumps will now add to the Eclipse navigation history, meaning that you can use Ctrl-I and Ctrl-O to go back and forward as well as Alt-Left and Alt-Right.
* `''` will still only work for Vrapper jumps, and it will only jump between the last positions within the same file.
* It will behave like Eclipse's navigation history and not like Vim:
  * When you go back in the history and make a new jump, all history entries you skipped will be lost. Vim on the other hand seems to return to the end and pushes a new jump onto the list.
  * Using `''` will still create a new jump entry, Vim seems to weed out such duplicates and reshuffles the list.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.55.20150526) which includes @albertdev's new behavior.  Please give it a try and let us know if there are any issues.  Sorry it took me so long to do a new build...

**Comment by haoadoreorange** [comment]
Hi! Sorry for digging up old thread.

> Using '' will still create a new jump entry, Vim seems to weed out such duplicates and reshuffles the list.

This seems to make '' jump back and forth only between 2 last positions. Is it intended ?

**Comment by albertdev** [comment]
@haoadoreorange That's how Vim behaves too: it jumps to the position before the latest jump, but running `''` is a jump as well, so repeating it with no other jumps in between will just move back and forth.
