### ISSUE TITLE
Home and End keys cancel visual mode

### ISSUE THREAD

**Issue by skybber** [vrapper/vrapper#503]
Home and End keys cancel visual mode instead select to end/begin of the line. I didn't find if this quite common problem would be reported. Excuse me if it was.

**Comment by albertdev** [comment]
I'm prototyping some new code where I might actually fix this problem without the need of unbinding Eclipse keys. That's no promise though, I just want to reuse it for tracking.

**Comment by albertdev** [comment]
Sadly I haven't gone anywhere with this yet.

My idea was to register a [IExecutionListener](http://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/bundles/org.eclipse.core.commands/src/org/eclipse/core/commands/IExecutionListener.java) to make Vrapper aware of various Eclipse actions, but I noticed that only the `preExecute` event can be counted on.

Then there's also the fact that the code managing Vrapper's visual mode needs refactoring to be called outside of it's keybinding state machine, so it might be a little longer before this gets completed.

**Comment by keforbes** [comment]
I'm going to close this defect.  We already know the workaround and the person who filed this defect closed it themselves.  @albertdev, you re-opened it for an investigation but it seems that investigation didn't work.  I don't think there's any other pending work here.  If you can find a way for vrapper to be aware of Eclipse actions that would be *amazing* but I don't think we need to track that work in a defect about the `Home` and `End` keys.
