### ISSUE TITLE
Cancelling a "/" or "?" search with the "incsearch" option on will also cancel the visual mode selection.

### ISSUE THREAD

**Issue by MrPay** [vrapper/vrapper#508]
With <code>:set incsearch</code>, type <code>v/</code> then type any text that causes the cursor to jump around as vrapper incrementally finds forward matches. (at this point, the entire visual marker/selection strangely disappears instead of following on to further encapsulate wherever the cursor jumps to, as in vim). Now press <code>&lt;Esc&gt;</code>. Instead of just cancelling the incremental forward search and staying in visual mode, the search is canceled and you're exited out of visual mode. Also happens with <code>?</code> command.

**Comment by albertdev** [comment]
@MrPay No idea if you still use Vrapper, but if you do, the next Vrapper release includes a fix for this issue. Pressing Escape (or repeated use of backspace) will now exit search mode without clearing the selection.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.51.20150205) which includes this fix.  If you get a chance, please verify the fix.  Thanks!

**Comment by loonies** [comment]
Yes, it fixes the "eclipseaction" bug.
