### ISSUE TITLE
Attempt to remap Camelcase motions commands cancels the visual mode

### ISSUE THREAD

**Issue by skybber** [vrapper/vrapper#526]
Excuse me if it is already solved. I've unmap ctrl+left from eclipse binding and try to remap it in .vrapperrc to support camelcase motion. It works for normal+insert mode.

nnoremap \<c-Left\> :WordPrevious\<cr\>
inoremap \<c-Left\> \<c-o\>:WordPrevious\<cr\>
eclipseaction WordPrevious org.eclipse.ui.edit.text.goto.wordPrevious

But for visual mode it cancels the mode. Is it posible to stay in visual mode in some way to support this feature?

vnoremap \<c-Left\> :WordPrevious\<cr\>

EDIT: I think it is common problem. Eclipse has a lot of cursor movement commands that could be used in visual mode without cancel the visual mode.

**Comment by keforbes** [comment]
I'm closing this issue.  The camelCase text object is now implemented as the subword optional plugin (see #460).  The defect you ran into while trying to implement a camelCase motion is being tracked as #511.
