### ISSUE TITLE
Integrate Eclipse's native bookmarks with vrapper marks

### ISSUE THREAD

**Issue by ChristianKleineidam** [vrapper/vrapper#537]
Vrapper supports vim's feature of setting a mark `k` via pressing `m` `k`. Currently that mark doesn't survive restarting Eclipse.
Eclipse also doesn't provide visual feedback for the existence of a mark. I imagine that the existing mark system breaks down when Eclipse does complex refactoring. 

Eclipse on the other hand has a native bookmark feature. It's bookmark survive restarting Eclipse. Existing Eclipse bookmarks get marked visually at the beginning of a line. Eclipse knows to handle it's own marks when it uses it's own refactor operations. 

I would therefore propose that vrapper uses Eclipses existing bookmark system for marks. There might be some added complexity as Eclipse's system focuses only on the line number but vrapper marks also track the position within the line but that information could be stored in the Eclipse bookmark name:
A bookmark might be named within Eclipse as: ``k : Char 20`

**Comment by keforbes** [comment]
I'm going to close this issue.  I only left it open because of a crazy idea I had which no one requested.  The intended request was already implemented though.
