### ISSUE TITLE
Autocomplete causes viwrapper mode to end

### ISSUE THREAD

**Issue by GaryFurash** [vrapper/vrapper#549]
I'm using Juno, Windows 8, Java 8. When I allow autocomplete to paste the right word in for me, (sometimes) vwrapper stops working - none of the keybindings work (it reverts to normal java editor). I have to close and reopen the editor window.

Not a big deal since this software is free and amazing!

**Comment by albertdev** [comment]
@GaryFurash 
I'm going to close this issue due to lack of information. Please reopen this issue if you feel that there is still a problem and you have more background information to help us fix it.
