### ISSUE TITLE
Support for <Leader> ?

### ISSUE THREAD

**Issue by hrj** [vrapper/vrapper#556]
If I set a mapping like this:
```
nmap <Leader>,   :
```

then the `<Leader>` seems to be ignored and the character `,` gets mapped to `:`.

Is / will this be supported?

**Comment by albertdev** [comment]
Both the `<Leader>` key and the `:let mapleader=` command are now implemented.

So far the only thing this is useful is for the subword motion plugin where the `:subwordmappings` helper command will define mappings using `<Leader>`.

**Comment by loonies** [comment]
Looks like it doesn't work if mapping is set in _vrapperrc_ file, but it
does work if set in command line.

Set _leader_ key and mapping in command mode (works)

    " Command mode
    :let mapleader='\'
    :nmap <Leader>x dd

Set _leader_ key in _vrapperrc_, mapping in command mode (works)

    " vrapperrc
    let mapleader='\'

    " Command mode
    :nmap <Leader>x dd

Set _leader_ key and mapping in _vrapperrc_ (doesn't works)

    " vrapperrc
    let mapleader='\'
    nmap <Leader>x dd

**Comment by albertdev** [comment]
Oops, it looks like `<Leader>` is in our "unsupported" list in the the `.vrapperrc` parser.

You can read above that I didn't really consider `<Leader>` to be useful for custom remaps so I didn't test for such remaps originating in `.vrapperrc`.

**Comment by keforbes** [comment]
@loonies, I've updated the unstable update site with a new build (0.69.20160613) which allows you to set `<leader>` in `.vrapperrc` now.

**Comment by loonies** [comment]
It works as expected. Thanks!
