### ISSUE TITLE
':substitute' with 'g' flag (':s/../../g') not deleting all occurrences.

### ISSUE THREAD

**Issue by ma-ti** [vrapper/vrapper#570]
When using ':substitute' with 'g' flag not all occurrences get deleted.
System: Vrapper 0.49, PyDev 3.8, Eclipse 4.3R2, Java 8, Windows 7

Example: return (buffers, sources)

Case 1: :s/[()]//g
Vrapper:return buffers, sources)
Vim: return buffers, sources

Case 2: :s/[ueo]//g
Vrapper: rtrn (bffrs, sources)
Vim: rtrn (bffrs, srcs)

**Comment by albertdev** [comment]
This will be included in the next release, to be released shortly.

**Comment by keforbes** [comment]
I'll release the next version this weekend.  Until then, I've updated the unstable update site with a new build (0.51.20150205) which includes this fix.  If you wouldn't mind, please verify this fix when you get a chance.
