### ISSUE TITLE
Returns to normal mode after hit `return` in a template

### ISSUE THREAD

**Issue by wangkaibule** [vrapper/vrapper#583]
When I simply type a `(` ,  Eclipse will add a `)` for me and put cursor in the middle of them. 

After I finish with the content between parentheses ,I can simply hit return, then the cursor will move to the place exactly where I want it to be (In this condition ,the cursor will move to the end of line ).

Thanks for the Eclipse template mechanism,  I can type quickly and smoothly .

However ,after I installed **vrapper** ( which is really good **:)**  ) ,I found that **vrapper** will return to normal mode when I hit `return` in a template.This is really not a big problem ,but do spoil the mood of typing ...

Please fix it !

press`(`  : ![image](https://cloud.githubusercontent.com/assets/8235508/5681554/790bead6-9854-11e4-955f-c4f751080924.png)       

difference before and after **vrapper** is installed when I hit `return` 
before : ![image](https://cloud.githubusercontent.com/assets/8235508/5681573/a88d7f22-9854-11e4-91ba-2312292e53a2.png)        after : ![image](https://cloud.githubusercontent.com/assets/8235508/5681598/d24fad1c-9854-11e4-8944-9600b3fe7cc0.png)

another example:                                  
![image](https://cloud.githubusercontent.com/assets/8235508/5681772/43ed897a-9856-11e4-93dd-ed20f863f1b1.png) 

 which turns out :     
![image](https://cloud.githubusercontent.com/assets/8235508/5681946/a34a35b6-9857-11e4-8401-cc17228fb0cf.png)

**Comment by keforbes** [comment]
This is actually a feature which people requested. They wanted to return to NormalMode after performing an Eclipse operation. To disable it, put ` set noexitlinkmode` in your `.vrapperrc` file. 

http://vrapper.sourceforge.net/documentation/?topic=configuration
