### ISSUE TITLE
:j commandline command to join lines

### ISSUE THREAD

**Issue by cirosantilli** [vrapper/vrapper#584]
By default Ctrl + Alt + J on Eclipse: http://stackoverflow.com/questions/2582939/join-lines-in-eclipse

**Comment by albertdev** [comment]
Vrapper does have line joining: just try pressing `J` in normal mode.

However, I could bind `:j[oin]` to that code if you want to. Any remarks on Vrapper's behavior of `J`?

**Comment by albertdev** [comment]
With regards to that last question: Vim seems to put the cursor at the beginning of the line after `:join` and in between lines after `J`. Eclipse on the other hand always seems to put the cursor at the end of the line.

I prefer to implement it the way Vim deals with it, for those who are used to do it there.

**Comment by cirosantilli** [comment]
True, `J` is good as well. Let's open new issues if we find details of `J`'s operation, but it's fine for me now.
