### ISSUE TITLE
Vrapper Disabled (and won't renable)

### ISSUE THREAD

**Issue by ozborn** [vrapper/vrapper#587]
Somehow (I'm not sure how) I managed to toggle off vrapper (Luna Eclipse).

After googling a bit I released there was an icon on my toolbar to re-enable vrapper, however when I click it the button, the text at the bottom of the screen (to the left of "Writable") still says "vrapper disabled" and clicking and re-clicking won't enable it again.

I upgraded from 0.48 to 0.50, tried restarting but it seems like the vrapper toggle button still isn't working. Honestly I didn't even know that button existed until vrapper stopped working. Any troubleshooting advice?

**Comment by albertdev** [comment]
It's possible that you hit a bug, although I can't recall if I have seen such a problem yet.

Could you open the "Error Log" view in Eclipse and check if there are any errors related to Vrapper in there?

That view also has a "Open log" button in it's top-right corner, if you click it you can view the log and copy any errors you might have to GitHub.

**Comment by ozborn** [comment]
There is a mention of a vrapper issue at the end of the log (shown below)

!SESSION 2015-02-02 16:29:36.358 -----------------------------------------------
eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/ozborn/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/ozborn/.eclipse_keyring -showlocation

!ENTRY org.eclipse.m2e.logback.configuration 2 0 2015-02-02 16:29:39.250
!MESSAGE Exception while setting up logging:org.eclipse.osgi.internal.framework.EquinoxConfiguration$1 cannot be cast to java.lang.String
!STACK 0
java.lang.ClassCastException: org.eclipse.osgi.internal.framework.EquinoxConfiguration$1 cannot be cast to java.lang.String
	at org.eclipse.m2e.logback.configuration.LogHelper.logJavaProperties(LogHelper.java:26)
	at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:189)
	at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
	at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
	at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

!ENTRY org.eclipse.core.net 1 0 2015-02-02 16:29:42.025
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.jface 2 0 2015-02-02 16:29:43.100
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-02-02 16:29:43.100
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.python.pydev.debug.setnext,Set Next Statement,
		,
		Category(org.python.pydev.ui.category.run,PyDev - Run,Python run category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@69f69078,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@13b29b34,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-02-02 16:29:43.100
!MESSAGE A conflict occurred for ALT+COMMAND+T:
Binding(ALT+COMMAND+T,
	ParameterizedCommand(Command(org.apache.uima.ruta.utils.apply.script,ApplyScriptCommand,
		,
		Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@25589735,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.refactor.quickMenu,Show Refactor Quick Menu,
		Shows the refactor quick menu,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@46994f26,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY org.eclipse.ui 4 0 2015-02-02 16:29:56.045
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NoSuchFieldError: INSTANCE)
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at net.sourceforge.vrapper.eclipse.jdt.keymap.JdtSpecificStateProvider.editJavaAndLeaveVisual(JdtSpecificStateProvider.java:95)
	at net.sourceforge.vrapper.eclipse.jdt.keymap.JdtSpecificStateProvider.visualModeBindings(JdtSpecificStateProvider.java:64)
	at net.sourceforge.vrapper.eclipse.keymap.AbstractEclipseSpecificStateProvider.initializeProvider(AbstractEclipseSpecificStateProvider.java:59)
	at net.sourceforge.vrapper.eclipse.platform.EclipsePlatform.buildPlatformSpecificStateProvider(EclipsePlatform.java:198)
	at net.sourceforge.vrapper.eclipse.platform.EclipsePlatform.getPlatformSpecificStateProvider(EclipsePlatform.java:156)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.<init>(DefaultEditorAdaptor.java:135)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory.createInterceptor(VimInputInterceptorFactory.java:123)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptAbstractTextEditor(InputInterceptorManager.java:104)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptWorkbenchPart(InputInterceptorManager.java:64)
	at net.sourceforge.vrapper.eclipse.activator.VrapperPlugin.restoreVimEmulationInActiveEditors(VrapperPlugin.java:116)
	at net.sourceforge.vrapper.eclipse.activator.VrapperStartup$1.run(VrapperStartup.java:13)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 23 more

**Comment by albertdev** [comment]
It looks like you have a version conflict...

How did you update? Can you check that all components are at version 0.50.0?

**Comment by ozborn** [comment]
That did the trick!

Somehow in my initial upgrade to 0.50 it must not have pulled in all the components?

I did a general check for updates, rebooted, and I am good to go. Thank you!

**Comment by albertdev** [comment]
Maybe you tried to install the new version from the marketplace instead of just searching for updated software?

Anyway, great to hear it got solved. Thanks for using Vrapper!

**Comment by jcastill0** [comment]
I know have the same problem. I can not re-enable vrapper. I tried uninstalling it and reinstalling it again from the MarketPlace. I'm using Luna (4.4.2) on MacOS X and the vrapper version is 0.56.0

Any ideas?

**Comment by albertdev** [comment]
@jcastill0 
Would you mind looking for your error log? See [my comment above](https://github.com/vrapper/vrapper/issues/587#issuecomment-72482632).

**Comment by jcastill0** [comment]
Copied below is my error log file right after startup of Eclipse
There are no references to vrapper

!SESSION 2015-08-07 17:24:23.658 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/jcastillo/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/jcastillo/.eclipse_keyring -showlocation

!ENTRY org.eclipse.core.net 1 0 2015-08-07 17:24:27.395
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.jface 2 0 2015-08-07 17:24:27.821
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-08-07 17:24:27.822
!MESSAGE A conflict occurred for ALT+COMMAND+A:
Binding(ALT+COMMAND+A,
        ParameterizedCommand(Command(de.bastiankrol.startexplorer.startSystemApplicationFromResourceViewCommand,Open Files With Default Application,
                Opens this file with the application that is registered for this file type in your operating system,
                Category(de.bastiankrol.startexplorer.commands.category,StartExplorer,null,true),
                org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7a8e484b,
                ,,true),null),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+A,
        ParameterizedCommand(Command(oracle.eclipse.tools.common.services.ui.dependency,Show Dependencies,
                Show dependencies for the selected item.,
                Category(oracle.eclipse.tools.common.services.ui.dependency.category,Dependencies,Dependency Related Commands,true),
                org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@643f8ebe,
                [Lorg.eclipse.e4.ui.internal.workbench.Parameter;@65013d71,,true),[Lorg.eclipse.core.commands.Parameterization;@30a99b85),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-08-07 17:24:27.822
!MESSAGE A conflict occurred for ALT+COMMAND+C:
Binding(ALT+COMMAND+C,
        ParameterizedCommand(Command(de.bastiankrol.startexplorer.copyResourcePathToClipboardFromResourceView,Copy Resource Path to Clipboard,
                Copies the path of the resource to the clipboard,
                Category(de.bastiankrol.startexplorer.commands.category,StartExplorer,null,true),
                org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@386d41cb,
                ,,true),null),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.ui.contexts.window,,,system)
Binding(ALT+COMMAND+C,
        ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.modify.method.parameters,Change Method Signature,
                Change method signature includes parameter names and parameter order,
                Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
                org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@20bf7206,
                ,,true),null),
        org.eclipse.ui.defaultAcceleratorConfiguration,
        org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY com.perforce.team.core 2 0 2015-08-07 17:24:29.291
!MESSAGE unable to get manifest version attribute: Not running from jar file: bundleresource://1929.fwk67928167:1/com/perforce/p4java/Metadata.class

!ENTRY com.perforce.team.core 2 0 2015-08-07 17:24:29.295
!MESSAGE unable to get manifest date attribute: Not running from jar file: bundleresource://1929.fwk67928167:1/com/perforce/p4java/Metadata.class

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.305
!MESSAGE P4Java server factory loaded; version: Internal 2010.1 Perforce Development; date: unknown

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.310
!MESSAGE Using default charset: UTF-8; JVM charset: UTF-8

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.315
!MESSAGE Checking this Java for symbolic link support...

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.327
!MESSAGE It seems this Java supports symbolic links.

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.331
!MESSAGE Symbolic link support at the OS level will be determined at runtime...

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.334
!MESSAGE initializing system file command helper class: java.io.File

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.338
!MESSAGE Using default RPC system file command helper: com.perforce.p4java.impl.mapbased.rpc.sys.helper.RpcSystemFileCommandsHelper

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.341
!MESSAGE setting RPC system file helper to class com.perforce.team.core.p4java.P4JavaSysFileCommandsHelper

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.407
!MESSAGE P4Java server factory called for Perforce server URI: p4jrpc://p4prd:1666

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.427
!MESSAGE Using Server implementation class: com.perforce.p4java.impl.mapbased.rpc.OneShotServerImpl

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.441
!MESSAGE Using program name: 'p4eclipse'; program version: '2014.1/965331'

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.445
!MESSAGE Using tmp file directory: /var/folders/v8/__vjrl3d3l5838bdz2ry75pxd19bf7/T/

!ENTRY com.perforce.team.core 1 0 2015-08-07 17:24:29.452
!MESSAGE connected to Perforce server at p4prd:1666

!ENTRY com.zeroturnaround.eclipse.optimizer.plugin 1 0 2015-08-07 17:24:43.548
!MESSAGE location of launcher INI: /Users/jcastillo/bin/eclipse/Eclipse.app/Contents/MacOS/eclipse.ini

**Comment by albertdev** [comment]
@jcastill0 
Are you willing to try installing from our new update site at http://vrapper.github.io/update-site/vrapper-stable/ ?

Featured on there is version 0.58.0.

**Comment by jcastill0** [comment]
I tried the new update, and it sill shows as disabled :-(

**Comment by albertdev** [comment]
Can you show a screenshot of which Vrapper plugins you have installed?

Go to Help > About Eclipse, then in that window click the Installation Details button. On the new window, go to the Plug-ins tab and enter "vrapper" as filter text.

**Comment by albertdev** [comment]
@jcastill0 

Can you show a screenshot of which Vrapper plugins you have installed?

Go to Help > About Eclipse, then in that window click the Installation Details button. On the new window, go to the Plug-ins tab and enter "vrapper" as filter text.

**Comment by jcastill0** [comment]
See attached image

**Comment by albertdev** [comment]
@jcastill0 
Seems like Github doesn't like it if you attach an image when mailing to their reply-bot. You will have to post it online somewhere or drag-and-drop it into a post on the Github website.

**Comment by jcastill0** [comment]
Try this link
https://drive.google.com/file/d/0B6DP39h3iDDvUWtNX19MdUpPeFk/view?usp=sharing

let me know when I can remove it.

thanks
