### ISSUE TITLE
Port of the indent block text object Vimscript (really handy for Python)

### ISSUE THREAD

**Issue by muellan** [vrapper/vrapper#591]
I recently did some things in Python and was happy to find out that the Eclipse PyDev plugin is quite nice. What I miss is the ability to select an indent block efficiently. A port of the indent block text object Vimscript would come in quite handy here and make a nice addition to Vrapper. Would also be useful for formatting Java or C++ code.

**Comment by keforbes** [comment]
I had no idea a vimscript like that existed.  It makes perfect sense though, I always want something like that when I'm in python.  Just for reference, is this the vimscript you're referring to?
http://www.vim.org/scripts/script.php?script_id=2484

**Comment by muellan** [comment]
I use this one: http://www.vim.org/scripts/script.php?script_id=3037 which in addition to lowercase ```i``` objects also has upper case ```I``` to include the line below the indent.

**Comment by keforbes** [comment]
@muellan, I've updated the unstable update site with a new build (0.53.20150214).  That build includes the indenttextobj optional plugin.  The plugin isn't quite done yet (I can't get the `I` feature working) but it should be usable enough in Python.  I'm not sure if the behavior is right when pasting but otherwise let me know if you run into any glaring issues.

**Comment by muellan** [comment]
cool, thanks! I'll try it right away.

**Comment by muellan** [comment]
The plugin works fine so far except that it treats empty lines differently. The vimscript "ignores" completely empty lines inside an indent block. If you are on an empty line and type for example  ```vii``` the original script will select the enire indent block surrounding that line. Your plugin will only select the empty line and the one following it. Since I use empty lines a lot to structure my source code this would be a bit annoying for me

**Comment by keforbes** [comment]
Thanks for the tip! I'll make sure to include empty lines.

**Comment by keforbes** [comment]
Ok, I've updated it to handle empty lines better and I got the `I` behavior working correctly.  At this point, I *think* I'm mimicking that vimscript correctly.  Let me know if I missed any other nuance in behavior.  Thanks!

Oh yeah, I've updated the unstable update site with a new build (0.53.20150216) which includes this change so you can try it out.

**Comment by muellan** [comment]
Hm, I can't update from the unstable site anymore. Is it just me or is something wrong with the site?
