### ISSUE TITLE
editor loses focus after changes are written with :w

### ISSUE THREAD

**Issue by mitchnull** [vrapper/vrapper#595]
if you make any changes to a file open in an editor and write the changes out with ":w" the editor pane loses focus, you'll have to click into the editor again to continue moving the cursor, etc.

this seems to be new with version 0.52.0.

**Comment by keforbes** [comment]
Yep, I can reproduce this in 0.52.0. `Ctrl+s` will still save without losing focus so at least there's a workaround.  

I think it might be worth releasing a 0.52.1 with this fix as soon as we have it; this defect will probably affect a lot of people.

**Comment by keforbes** [comment]
Ha, I just noticed that `:wa` (write all) doesn't lose focus.  So that's probably a better workaround for the time being.  I don't know how `:w` would lose focus while `:wa` would work correctly though. Weird.

**Comment by albertdev** [comment]
I can't reproduce this as easily on Windows...

@mitchnull What operating system and Eclipse do you use?

**Comment by mitchnull** [comment]
OS:
Linux 3.18.6-1-ARCH

eclipse:
Version: Luna Service Release 1a (4.4.1)
Build id: 20150109-0600

**Comment by mitchnull** [comment]
Strange, now I can't reproduce the issue either...

ah, hah... after a :wa, :w is "fixed", too ;)

**Comment by keforbes** [comment]
I was able to reproduce this on windows but you're right, after a `:wa`, `:w` starts working again. Huh.

**Comment by albertdev** [comment]
Weird...

Testing with Luna 4.4 20140612-0600 - Reproduced.
Testing with Luna 4.4 SR 1 20140925-1800 - No repro.

One of the weird things though is that F12 no longer works, normally that should restore focus to the editor. It looks as if the workbench thinks the editor is focussed yet it somehow lost that.

**Comment by keforbes** [comment]
I'm starting to think this defect is obscure enough that it may not warrant a 0.52.1 release.

**Comment by albertdev** [comment]
It seems my change in a487671 introduced enough subtle focus problems that Eclipse actions would also lose focus (click the commit id to see the comments from @igrekster and @loonies).

Since then I've pushed a rollback of my changes from the aforementioned commit, and maybe we should release a hotfix 0.52.1 as well.

Sorry for the trouble I've caused.

**Comment by keforbes** [comment]
I've updated the *stable* update site with a 0.52.1 release.  Please verify the fix.  If someone can confirm the problem is solved with no new side effects I'll announce the release on the webpage and update the direct download zip file later today.  I need to get ready for work now.

**Comment by loonies** [comment]
Yes, it fixes the "eclipseaction" dialog bug.

**Comment by mitchnull** [comment]
Works for me, too, thanks.
