### ISSUE TITLE
:w Sometimes causes cursor to disappear in Java editor

### ISSUE THREAD

**Issue by lukedegruchy** [vrapper/vrapper#597]
Sometimes when editing a Java file in Eclipse the cursor in the editor window disappears after typing :w in command mode and then hitting enter.  It's not clear where the focus goes as the cursor just doesn't seem to return from the command line (where :w is).

I've experimented on a number of files and it's not clear what the causal factors are.  It's not as simple as line number counts.

There are no errors in the Eclipse workspace logs when this happens.

This bug was introduced recently because I only noticed it after installing the latest version of vrapper.

Please let me know where I should look to give you more helpful data.

**Comment by keforbes** [comment]
I just released 0.52.1 yesterday which should fix that exact issue.  Try updating to latest again and if you're still seeing the issue then let us know.  Thanks!

**Comment by lukedegruchy** [comment]
I just installed 0.52.1 and have aggressively tried to reproduce this issue and thus far it seems to be working correctly.

**Comment by keforbes** [comment]
Great! I'm glad I already had a solution ready for you.  :)
