### ISSUE TITLE
character after 'y' in normal mode in a macro is repeated twice

### ISSUE THREAD

**Issue by ekucks21** [vrapper/vrapper#601]
If no one else is seeing this (v 0.52.1) then maybe it's something weird in my _vrapperrc. If I store a macro in "m, type 'yte', and then do ':reg m', I see 'ytte'. Same goes for other characters.

**Comment by albertdev** [comment]
I've made a few attempts to reproduce your issue but I have made no progress. I'm marking this as Unconfirmed until we find the combination of settings which trigger it.

Do you have a remapping for `y` in your `.vrapperrc`?

**Comment by ekucks21** [comment]
It did turn out to be a setting in my vrapperrc. Thanks.
