### ISSUE TITLE
the key bindings is non-vi when editing html file

### ISSUE THREAD

**Issue by redguardtoo** [vrapper/vrapper#602]
besides, `:split` does not work

0.52.1

**Comment by albertdev** [comment]
Do you have some more info on your Eclipse install? Is it the Java EE version or some version with extra HTML plugins installed?

About the `:split` command, did you install Vrapper from the marketplace without doing an extra update from our update site? The one on marketplace is a "light" version.

**Comment by redguardtoo** [comment]
yes, I install it from eclipse marketpace.

I also install eclipse color theme except your plugin. eclipse 4.3.2, Jave EE version.

**Comment by keforbes** [comment]
If you go to "Install New Software" and select the Vrapper update site you'll see some optional plugins.  One of the optional plugins is the Split Editor Plugin which will enable the `:split` commands.

**Comment by redguardtoo** [comment]
I already installed all plugins.

**Comment by albertdev** [comment]
Indeed, your screenshot shows you have pretty much all plugins installed except special language support for Java, though that shouldn't matter for HTML.

What do you see in your normal editing session then? Does it keep saying "vrapper disabled" at the bottom even when you click the "Vim" icon in the toolbar?

Can you open the "Error log" view and check if there are any errors related to Vrapper in there? If you want to copy/paste any errors, click the small "Open log" icon on the right side of that view.

**Comment by albertdev** [comment]
@redguardtoo Did you have any time to find the log file or have you got Vrapper working?

I've been thinking though, if the HTML editor you are using is a special one from IBM then it is possible that we don't activate Vrapper in it. We do assume that editors extend standard Eclipse editors, otherwise we can't query them for all their internals.

Where did you get your Eclipse? Is this a custom distribution by IBM or did you add those plugins by yourself?
Can you try to open a basic "Text file" and see if Vrapper is working there?

**Comment by redguardtoo** [comment]
I don't know, it's pre-configured text editor by my employer. basic text file is fine, issue only happens on html edtior.

**Comment by keforbes** [comment]
Vrapper extends the behavior of AbstractTextEditor, which is a base Eclipse class.  If your employer's custom HTML editor doesn't extend that class then Vrapper will be disabled whenever you use that editor.  I'm afraid there's nothing we can do here.

**Comment by albertdev** [comment]
@keforbes 
I was trying to get a trial version of RAD to look at this problem because it could also be something in our multi-part editor code. I might reopen this issue when I get RAD running and reproduce the problem.

**Comment by agelbess** [comment]
Had the same problem, I was using the "JBOSS Tools HTML Editor".
When I changed to the _plain_ "HTML Editor" vrapper started doing its magic.
To fix it, right click an HTML file and select "Open With"->"HTML Editor"
