### ISSUE TITLE
Some block-wise visual mode commands broken

### ISSUE THREAD

**Issue by rasup** [vrapper/vrapper#604]
When I select a block of text using `<C-V>` and use either `c` or `s` on that selection only the text selected on the first line gets changed (after pressing `ESC` of course).

Also, if I use the `r`, `x` or `d` command on a block of text *after* trying to change the text (like above), undoing needs to be done using the `u` command more than once (once per changed line).

I'm using 0.52.1 and have also tried the newest unstable.

**Comment by albertdev** [comment]
Indeed, it seems this got broken at some point. Marked as a defect.

**Comment by albertdev** [comment]
I haven't figured out a fix, but I did trace the problem back to the 0.50.0 release, more specifically commit 22025355db79f8ef2785402846087cf2457d7f20.

I'm adding some extra tests and I'll see what I can do in the next few days.

**Comment by albertdev** [comment]
Found the problem: the change operation has some weird code to detect if we're executing from blockwise mode or somewhere else. I'll try refactoring it.

**Comment by albertdev** [comment]
Right, I had a fix on Friday but forgot to push it. This will be fixed in the next release and unstable version.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150307) which includes this fix.  @rasup, please install this latest version and let us know if you have any other problems with it.  Thanks!
