### ISSUE TITLE
Red status bar message won't disappear

### ISSUE THREAD

**Issue by nbdsp** [vrapper/vrapper#610]
When the following is typed in the normal mode in Eclipse/PyDev 
: 22 o<CR>
in the status bar a red message 
"Unknown operation for range: o" 
appears which persists even after other commands has been run and can't be removed. Is there a way to remove such messages from the status bar?

**Comment by albertdev** [comment]
Normally such messages disappear after pressing `ESC` a few times, though most of the time I find that it goes away by itself.

Please check the Eclipse error log if this issue persists, there might be something related to Vrapper in there.

**Comment by keforbes** [comment]
I can't reproduce this defect.  If I do `:22 o` I see the error message but as soon as I hit any other key (even `j`) the message goes away.  Which build are you using?

**Comment by nbdsp** [comment]
I today upgraded Eclipse and Vrapper to the latest versions: 4.4.2 and 0.46.0 - but the problem still persists. I checked error logs, but there is nothing related to Vrapper. Actually it seems that all red error messages in Eclipse status disappear only if they are replaced with other error message. If, for example, one clicks on a file in the PyDev package explorer, the Vrapper error message in the status bar is replaced with "1 file selected", but it is shown again when one clicks in the editor window. I could not find any way to get rid of it. Maybe the problem is caused by some custom Eclipse settings, though, if there are ones that can be related to this issue.

**Comment by albertdev** [comment]
Wait, are you sure you are using a correct Vrapper update site? Vrapper is at this moment at version 0.52.1, the fix I was talking about was made in 0.48.0.

**Comment by nbdsp** [comment]
I used "net.sourceforge.vrapper.feature.group" for updating. After changing to "http://vrapper.sourceforge.net/update-site/stable" the version was upgraded to 0.52 and the issue gone. Thanks for helping.
