### ISSUE TITLE
Looks like count:s/patterna/patternb doesn't work correctly

### ISSUE THREAD

**Issue by wafflette** [vrapper/vrapper#611]
For example if i have 2 lines of code:
line 1: patterna blah1
line 2: patterna blah2

and i put the cursor on line 1 and type 2:s/patterna/patternb

the expected outcome is both instances of patterna are replaced with pattern b in 2 lines, however the command fails.

**Comment by albertdev** [comment]
Wait, what does the commandline look like?

Is it really `:2:s/patterna/patternb`?
Is there an error message on the bottom left?

**Comment by wafflette** [comment]
the command is
2:s/patterna/patternb
without the leading : in your example. In regular vim it automatically translates to      :.,.+1s/patterna/patternb

**Comment by wafflette** [comment]
I believe the general issue is that any previously queued count before the initial  :  should be translated to  .,.+(count-1) in the vim command line, ie if i type 10: in regular vim, it will pop up as :.,.+9

**Comment by keforbes** [comment]
Vrapper simply doesn't have support for this feature, that's why it isn't working.  This would be a feature request.  Can you find a description of this feature in the Vim docs?  I want to make sure I understand what the behavior is supposed to be.

**Comment by wafflette** [comment]
Seems more like a bug to me but i guess you could call it a feature. It's a part of core vim philosophy that any action can be prefixed with a count to specify the scope or the number of time it's repeated.

**Comment by wafflette** [comment]
The description is just that:
any previously queued count before the initial : should be translated to .,.+(count-1) in the vim command line, ie if i type 10: in regular vim, it will pop up as :.,.+9 for the range.

**Comment by albertdev** [comment]
@keforbes It is [documented as `N:`](http://vimdoc.sourceforge.net/htmldoc/cmdline.html#N:).

@wafflette Thank you for your interest in Vrapper. We don't claim that we support every feature Vim and implement most of them on an as-needed basis.

The distinction is mainly for internal use. Bugs may impact several existing Vrapper users and receive higher priority, whereas feature requests mostly mean that a single user is blocked from working efficiently but likely has a workaround. We try to fix the latter when time and knowledge of the problem is available.

**Comment by albertdev** [comment]
@wafflette
While I was stuck on #612 I looked at a way to implement this, but it looks like it does nothing more than filling the command line with `:.,.+2`?

As a workaround you can enter that by hand, though I also have some code ready which can automate it.

**Comment by albertdev** [comment]
This should be available in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150318) which includes this fix.  Please give it a try and let us know if you run into any other problems.  Thanks!

**Comment by wafflette** [comment]
Yes, this seems to be correct now, thanks so much!
