### ISSUE TITLE
Clipboard contents (and corrosponding register) empty after yank in visual block mode

### ISSUE THREAD

**Issue by robertszalapski** [vrapper/vrapper#617]
Common use case is copying commented multi-line commands to paste directly on 
```
# Example:
# echo \
#   some \
#   wrapped \
#   text \

```
After `jll<Ctrl+V>}$` I expect the clipboard contents to contain the shell command.  Instead, they are empty.  The anonymous register has the text and pastes correctly within eclipse.  Text copied in visual line mode enters the clipboard register as expected.

**Comment by keforbes** [comment]
Interesting, if this works in visual line mode but not in visual block mode then it's probably just a simple oversight to not handle the scenario in visual block mode.  In your example string, `jll<Ctrl+V>}$`, I assume there should've been a `y` at the end right?  Or were you expecting the clipboard to automatically update as the selection changes?

Also, this probably isn't relevant (since your scenario worked in visual line mode) but we do have support for the `:set clipboard=` property if you need it:
http://vrapper.sourceforge.net/documentation/?topic=configuration

**Comment by albertdev** [comment]
Actually, is it possible that you're using `set clipboard=autoselectplus,unnamedplus` or something similar in your `.vrapperrc`? Easiest way to check is to do `set clipboard?` in Vrapper itself.

**Comment by robertszalapski** [comment]
Er, yes, there should be a y at the end of the command. This is explicit yanking failing to be in the register for the system clipboard when in visual block mode. Yanking works as expected otherwise. Let me know if you need more info. Thanks!

**Comment by albertdev** [comment]
Just to make sure that I didn't miss anything:

* `jll<Ctrl+V>}$y` works correctly in 0.52.1. It yanks to the anonymous register after which you can paste it anywhere within the same Eclipse instance. The clipboard is not changed (seemed also OK). Doing this in other visual models works similarly.

* `jll<Ctrl+V>}$"+y` yanks the block to the clipboard without modifying the anonymous register and should allow pasting in other Eclipse instances as well as Notepad. When pasting in Notepad, it looks as if you copied 3 whole lines with just the contents of the block. This was broken in version 0.52.1; you can yank/paste between Eclipse instances but other applications couldn't interpret the clipboard contents. My commit makes sure that this text representation is also available.

This change will be included in the next unstable and release build.

**Comment by keforbes** [comment]
Sorry it took so long for me to do a build.  I've updated the unstable update site with a new build (0.53.20150327) which includes this fix.  Please give it a try and let us know if it works for you.  Thanks!

**Comment by robertszalapski** [comment]
No problem.  The unstable site was down a few times when I tried, but now the update site is working and the block mode paste works as expected.  Thanks!  This will save me some annoyance.  :+1:   (My workaround had been using visual block mode to delete the comments, yanking the command in visual line mode, then undoing the comment deletion. )
