### ISSUE TITLE
:let @*=@3 doesn't work

### ISSUE THREAD

**Issue by robertszalapski** [vrapper/vrapper#618]
I often copy stuff between registers in vim, eg `:let @*=@%` or `let @+=@/` or whatever.

Unfortunately, in VRapper, it incorrectly puts the literal string after the equals into the register, instead of putting in the specified register contents.

**Comment by keforbes** [comment]
This reminds me of @albertdev's comment in #577
> Ah, Vim allows such creative abuse of registers...

The reason that doesn't work is because it was never implemented.  However, since @albertdev recently added support for `:let @/ = ""`, this new abuse of registers should be possible.  I'll mark this as a feature request.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150318) which includes this fix.  Please give it a try and let me know if I messed anything up.  Thanks!

**Comment by robertszalapski** [comment]
That was a really quick fix, thanks!  Works fine here.
