### ISSUE TITLE
":set smartcase" doesn't seem to be working

### ISSUE THREAD

**Issue by wafflette** [vrapper/vrapper#620]
This feature is supposed to ignore case if all input letters are lowercase and respect case otherwise.

**Comment by albertdev** [comment]
@wafflette
It seems that I can't reproduce this, doing `set smartcase` gives no error and searching uppercase or lowercase does have an effect.

Did you enable [`ignorecase`](http://vrapper.sourceforge.net/documentation/?topic=configuration)? Vim requires it to be set before `smartcase` has any effect.

**Comment by wafflette** [comment]
Hmm. Looks like the problem is that my .vrapperrc is not executing for some reason. Otherwise if i set ignorecase and then smartcase then it works.
