### ISSUE TITLE
.vrapperrc not loading

### ISSUE THREAD

**Issue by wafflette** [vrapper/vrapper#622]
Any ideas why this might be? My settings are not loading.
Here's my ~/.vrapperrc file:
```
set shiftwidth=4
set tabstop=4
set expandtabs
set ignorecase
set smartcase
set hlsearch
set softtabstop=4
```

**Comment by keforbes** [comment]
Is .vrapperrc spelled correctly? Or maybe a permissions issue?  Are there any errors in the Eclipse log?  I'm not sure what would prevent .vrapperrc from loading.

**Comment by muellan** [comment]
I have the same problem with a second eclipse installation on a different machine. Since I use that PC not that often I did not bother to investigate (just sourced the .vrapperrc on every new editor there). The interesting thing is: the 2nd eclipse was an exact copy of my other eclipse that I work with and that loads the .vrapperrc correctly. Both are Windows 8.1 64bit installations with 32bit eclipses and Java 1.8.

**Comment by wafflette** [comment]
The name of the file is spelled correctly and permissions are 777. I actually don't have Eclipse error log (nothing like that under window/show view anyway).

**Comment by wafflette** [comment]
Btw how do you source a file? :so doesn't seem to be working.

**Comment by wafflette** [comment]
There was actually 1 error in the file - :set expandtabs should be :set expandtab but it doesn't load even after i fixed that.

**Comment by keforbes** [comment]
Huh, well I'm stumped.  I'm on Ubuntu 14.10 with Eclipse 4.4 (Luna) and it's working fine.  I'm not even sure what else to try if you don't have any errors in your error log.

**Comment by albertdev** [comment]
If you go to Help > About > Installation Details > Configuration tab, can you check if the directory listed next to `user.home` is the one your `.vrapperrc` is in?

**Comment by wafflette** [comment]
So yeah, mystery solved :) Thanks!

```
user.dir=/home/wafflette
user.home=/root
user.language=en
user.name=root
```

**Comment by albertdev** [comment]
I'm going to see if I can add some warning in the log printing out `couldn't find $home/.vrapperrc`. That should at least make it more obvious were the rc is expected.

Can't say if it will be in this release though, the trouble will be to print it just once.

**Comment by muellan** [comment]
Problem solved for me as well!
