### ISSUE TITLE
:so abbreviation doesn't work - should map to :source

### ISSUE THREAD

**Issue by wafflette** [vrapper/vrapper#624]
:so produces an error "not an editor command: so"

**Comment by keforbes** [comment]
Looks like the issue is that it's conflicting with `:sort` and `:source`.  Anytime a collision like that happens I have to explicitly define a shortened version of the command (`:so`) so it calls the right operation.  I can verify that `:sou` works correctly since that doesn't produce a collision.

**Comment by keforbes** [comment]
I've fixed this defect but it isn't in the updated build.  You'll have to use the workaround of typing `:source` until I do a new release this weekend.
