### ISSUE TITLE
Implement C-T

### ISSUE THREAD

**Issue by sschaef** [vrapper/vrapper#626]
It looks like `C-T` is not implemented. When I do a `C-]` in order to jump to the declaration nothing happens if I press `C-T` afterwards.

A stack tag is probably not implemented in vrapper, but it could still jump back to the location of the cursor before `C-]` was pressed.

**Comment by keforbes** [comment]
You're right, we haven't implemented tags.  Can you use `''` to jump back to the previous location?

Also, we have `Ctrl-I` and `Ctrl-O` to move forward and backward through Eclipse's navigating history but I've had mixed results with the way Eclipse handles its navigation.

**Comment by sschaef** [comment]
`''` doesn't work on different files, it only jumps between the positions of a same file, but `C-I` and `C-O` is good enough for me, thanks. No need for `C-T` anymore.

**Comment by albertdev** [comment]
I guess a workaround would be to map `C-T` to `C-O` as Eclipse already does the heavy lifting for definitions.

Mind you, that thing about `''` is logged as feature request #487, and I haven't even fixed my own pet peeves...
