### ISSUE TITLE
Bugged behavior with record and ctrl [

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#628]
As some of you vim gurus no doubt know, ctrl + [ is a very useful alias for Esc. This is my preferred way to return to normal mode. Unfortunately, it has the following bugged behavior when recording a macro.
1) hit qa to begin recording to the 'a' register
2) hit 'i' to enter insert mode, then type the word "hello", and hit ctrl + [, then q to stop recording
3) type @a
4) The output is "hello["
I actually was unsure at first if this is what's supposed to happen, but it a) works with Esc, and b) works in vim.

**Comment by albertdev** [comment]
Marked as a defect. It seems we don't properly store `Ctrl-`something keystrokes into a register...

**Comment by albertdev** [comment]
It seems I broke this with commit 68e0387876f51b19aa7e73c14924e08a6d51c306 back in 2013. I have a fix and will do some more testing.

**Comment by quicknir** [comment]
Wow, amazing turn around time! Thanks!

**Comment by albertdev** [comment]
You're welcome, turns out this one wasn't too complicated.

I see that @keforbes just did an unstable release, this means this fix will only be in the next unstable and release build.

**Comment by keforbes** [comment]
While it's true I just did an unstable build, it's simple enough to do another one.  I've updated the unstable update site with another build (0.55.20150419) which includes this latest fix.

I haven't committed my changes to those Eclipse build files, I'm not sure if that's really something I need to keep doing with every unstable build...
