### ISSUE TITLE
question about relative numbering

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#630]
Hello, I'm aware that there is a plugin that provides relative line numbering. Unfortunately, while I was able to download the software, the site with instructions is down. I tried to contact the author, he said he'd take a look at the site when he could. I was hoping someone here had installed it and could tell me how? 

I realize this is low priority, but if the author of the other plugin is willing it might be good to integrate his code directly into VRapper. It would be nice to set it vim style, and have that code be part of an active project. 

Sorry if this is not the right forum to ask this question.

**Comment by albertdev** [comment]
What plugin are you talking about?

http://matf.github.io/relativenumberruler/ still seems to exist...

**Comment by quicknir** [comment]
Hey Albert, that's the one I mean yes. If you follow the link you posted, it mentions another site. But when I try to go to that url, it's down. The plugin still exists but it seems not too active, no updates on github for a while and the site with instructions down. 

Good to know, it was

**Comment by quicknir** [comment]
Just a thought. Hit close issue by accident :-)

**Comment by albertdev** [comment]
You mean that you clicked on `http://matf.github.io/relativenumberruler/updatesite/` and were surprised that it is nearly empty?

I believe that URL is only meant to be used as in Eclipse as an update site, see [Installing new software](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-124.htm).

The fact that the plugin isn't updated isn't a bad sign: it only does one little thing, and as long as it isn't broken it doesn't need fixing.

**Comment by quicknir** [comment]
Ah, thanks very much, I was very confused. Elsewhere on the site it suggests to click on that link for further instructions, and when I clicked on it it wouldn't load. I had no idea it was intended to be used directly in eclipse like that. I got it working, and it works perfectly. Thanks!

**Comment by matf** [comment]
I have clarified the README of the [relative line number plugin](https://github.com/matf/relativenumberruler) somewhat regarding installation instructions.

As for licensing, if I remember correctly, this code was derived from some EPL-licensed Eclipse code, so it would most probably be less of a hassle to just rewrite the few lines of code it consists of. Until then, I guess the plugin should work as it is.
