### ISSUE TITLE
Cannot increment numbers over 0x7FFFFFFF

### ISSUE THREAD

**Issue by pa0los** [vrapper/vrapper#631]
I'm using the Ctrl+A shortcut to increment hexadecimal numbers. Everything works as expected until you reach the value 2^31 = 0x7FFFFFFF.
This is probably because the variable holding value is INT instead of UNSIGNED INT or LONG.
Should be easy to fix :-)

**Comment by albertdev** [comment]
This will be included in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.55.20150426) which includes this fix.  You can go ahead and start using your own fix now. :smile:
