### ISSUE TITLE
Add support for manipulating folds in PyDev

### ISSUE THREAD

**Issue by keforbes** [vrapper/vrapper#635]
Vrapper's normal `zc`, `zo`, `zM`, `zR` features call Eclipse commands to do the folding.  However, if you try using any of those folding commands in PyDev today Eclipse throws an error:
```
NotHandledException: There is no handler to execute for command org.eclipse.ui.edit.text.folding.collapse
```

It seems this is because PyDev defines their own custom commands:
```
org.python.pydev.editor.actions.navigation.pyCollapse
org.python.pydev.editor.actions.navigation.pyUnCollapse
org.python.pydev.editor.actions.navigation.pyCollapseAll
org.python.pydev.editor.actions.navigation.pyUnCollapseAll
```

We need to update our optional Python plugin to override the Eclipse commands and use PyDev's commands instead.

**Comment by keforbes** [comment]
I *thought* this would be as simple as adding a new block to `PyDevSpecificStateProvider`:
```
transitionBind('z',
    leafBind('o', (Command)action("navigation.pyUnCollapse")),
    leafBind('c', (Command)action("navigation.pyCollapse")),
    leafBind('R', (Command)action("navigation.pyUnCollapseAll")),
    leafBind('M', (Command)action("navigation.pyCollapseAll"))),
```

Unfortunately, when I did this, it still tried executing the old commands (and failed).  @albertdev, I'm hoping you can remember what special magic is needed to override an Eclipse command in our optional plugins.

**Comment by keforbes** [comment]
Also, as a side note, we currently have a `ToggleFoldingCommand` class to implement the `za` feature.  Eclipse didn't have a "toggle" command so we basically execute an 'expand' command and see if the view changed.  If it didn't, we then execute a 'collapse' command.  While investigating this defect, I found that Eclipse now has a command:
```
org.eclipse.ui.edit.text.folding.toggle
```
We may be able to throw away `ToggleFoldingCommand` and use this command instead.  We'll have to check to see which Eclipse version introduced this command though, it probably isn't backwards-compatible.

Sorry, that's all the time I can spend on this defect, gotta run.

**Comment by albertdev** [comment]
@keforbes 
Looks like our keybinding code is not properly prioritized... I'll take a look at it tomorrow. Thanks for doing the research.

**Comment by keforbes** [comment]
Thanks @albertdev! This was a request from the forums so I appreciate the quick turnaround.
https://sourceforge.net/p/vrapper/discussion/901741/thread/5c9ebec4/
