### ISSUE TITLE
Copy to clipboard with vrapper

### ISSUE THREAD

**Issue by ajeebkp23** [vrapper/vrapper#643]
I am very much happy with vrapper and i use it day to day life. Still i see a feature is missing.
In vim, i add these three lines to `~/.vimrc`.Thus, Yanking(copying) text to be saved into clipboard of os.
This might be helpful if someone uses a clipboard manager or some thing like that.

`
if has('unnamedplus')
set clipboard=unnamed,unnamedplus
endif
`
I tried adding the same into `~/.vrapperrc`, didn't work.
Is it possible  to make same happen in vrapper?

**Comment by albertdev** [comment]
Vrapper doesn't support `if`, but it should support the `clipboard` option. Have you tried it without the `if` yet?

**Comment by ajeebkp23** [comment]
Sorry, for complaining.
Once i removed if conditioning it worked like a charm in Eclipse Luna.
Thus,I used this line instead.
`set clipboard=unnamed,unnamedplus`
