### ISSUE TITLE
The "sort" command adds extra line

### ISSUE THREAD

**Issue by loonies** [vrapper/vrapper#644]
Consider this example

~~~
foo
bar
baz

Something...
~~~

 1. Select the first 3 lines (visual line selection)
 2. Execute `:'<,'>sort`
 3. The 5th line is added

Result

~~~
bar
baz
foo


Something...
~~~

Expected

~~~
bar
baz
foo

Something...
~~~

**Comment by keforbes** [comment]
Huh, you're right, I can reproduce it.  But sometimes I can get that behavior and sometimes I can't.  I tried switching between visual line mode and regular visual mode but I don't see any pattern in when it happens and when it doesn't.  In fact, I can reproduce it more reliably with regular visual mode (`v`) than with visual line mode (`V`).  Weird.

**Comment by loonies** [comment]
This worked as expected, but got broken (not sure when, though).

**Comment by albertdev** [comment]
I can't reproduce it at all using visual line mode... Can you check if it differs for a file with Windows end lines or Linux end lines? So far I see no change.

There must have always been a bug in it for plain visual mode though: I just noticed in a fresh test that it doesn't properly convert a visual selection length to a line-wise length, even though the operation works in linewise mode.

For example, select from the last "f" on the first line to the "b" of baz and do a sort. The output now contains the following:

    bar
    baz
    foo
    az

So far this doesn't happen using visual line mode on Windows...

**Comment by loonies** [comment]
Wooops, sorry, my bad. It works with visual line `V`, but not regular
visual `v` mode, selection like `vip`, or `Vip`.

Workaround to this problem is to move cursor to the other corner of
visual selection (`o`), and then execute `:<'>'sort`.

> For example, select from the last "f" on the first line to the "b" of
> baz and do a sort.

Yes, I can confirm the same behaviour.

**Comment by albertdev** [comment]
I completely reworked the internals of ex commands after finding that they duplicated all kinds of bits of code.

Normally everything should work more consistent now that I moved out the range-finding code to a central class `SimpleLineRange` and leave the conversion for `AbstractLineWiseOperation`.
