### ISSUE TITLE
Ctrl-O/Ctr-I and Eclipse back/forward question

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#645]
Hello,

This is not so much an issue as a question. It seems like Ctrl-O/Ctrl-I are just mapped precisely to eclipse back and forward. However, these commands will not work if you are in a tab where Vrapper is not active (not so shockingly). The main example I have is when you launch a build and a Console pops up, it's common and desirable to be able to go "back" to the last editor you were in. This doesn't work with Vrapper. Isn't it just preferable then to directly map Ctrl-O/Ctrl-I so they work everywhere? Is there something I'm missing?

Nir

**Comment by keforbes** [comment]
You're right, we're just using Eclipse's history navigation commands for `Ctrl-O`/`Ctrl-I` and we don't have any control over anything outside of an editor.  By default, Eclipse maps those same commands to `Alt-Left` and `Alt-Right`.  Can you map Eclipse's "Backward History" (`Alt+Left`) and "Forward History" (`Alt+Right`) to use `Ctrl-O` and `Ctrl-I` instead?  It would override Vrapper's mapping to those commands but they're the exact same operations anyway and if Eclipse has the mapping then it should be available throughout all of Eclipse.  At that point you'll just be using Eclipse features so if anything goes wrong it would be unrelated to Vrapper.

Does that answer your question?  Or did I misunderstand something?

**Comment by quicknir** [comment]
That's good to know. I think it might be worth mentioning this in the documentation, as far as I can see this would be strictly preferable to doing it in Vrapper. Thanks for your response!
