### ISSUE TITLE
clang-format plugin doesn't use .clang-format file

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#646]
It seems like the clang-format plugin does not use a .clang-format file located in a directory above the source file you run it on. This makes the clang-format plugin in its current form more of a curiosity than practical for 95% of people; most people don't use exactly the google or llvm style, but rather dump the .clang-format file using one of those as a baseline, and then tweak it significantly.

Perhaps it would make sense to either a) fix this issue, probably not too hard, or b) it may be quite trivial to hook into the existing clang-format plugin for Eclipse which works quite well; the only challenging part would be getting it to work properly with line ranges.

**Comment by igrekster** [comment]
I'm using the `clang-format` plug-in in the _file_ mode. I have the following commands in my `.vrapperrc` 
```
clang-format-default-style file
nnoremap gC :.clang-format<SPACE>file<CR>
vnoremap gC :clang-format<SPACE>file<CR>
```
What editor are you using? Do you get an error in the "Error Log" related to `clang-format` ?

**Comment by albertdev** [comment]
@quicknir 
Is that sufficient information?

**Comment by quicknir** [comment]
Haven't had a chance to test it yet, but I'll try to take a look. I don't remember the 'file mode' being documented, but it's probably just poor reading skills on my part.

**Comment by quicknir** [comment]
This works perfectly, it seems like I'm just an idiot. As always, thanks to @albertdev and all the people who put time into Vrapper and make it so awesome, and thanks to @igrekster for the info.
