### ISSUE TITLE
Use 'J' key to move down in Eclipse popups

### ISSUE THREAD

**Issue by mmbradle** [vrapper/vrapper#648]
Question
---------
Is there a way to get <kbd>j</kbd> to move to the next result in the Eclipse auto-complete popup when using Vrapper?

Rationale
---------
When I use Eclipse's auto-completion (<kbd>Ctrl</kbd>+<kbd>Space</kbd>) or quick-fix (<kbd>Ctrl</kbd>+<kbd>1</kbd>), I would like to use the <kbd>j</kbd> and <kbd>k</kbd> keys to move to the next and previous match. I get so used to moving this way in Vrapper that it is a bit hard to switch tactics in the specific Eclipse situations that Vrapper does not control. The auto-complete popup is the most common of these situations for me. 

Possibilities
-------------
I see several possibilities for solving this:

 1. Perhaps Vrapper can solve this problem internally (if it isn't solved already)
 1. Create a key combination in Eclipse if the command for this is exposed
 1. Create a key combination outside of Eclipse that sends a <kbd>&darr;</kbd>
 1. Live with using the <kbd>&darr;</kbd> key
 1. Perhaps there is a .vimrc trick such as mapping <kbd>j</kbd> to <kbd>&darr;</kbd>and Eclipse will capture that <kbd>&darr;</kbd>

Also, please let me know if this isn't the correct place to post this question.

**Comment by keforbes** [comment]
We have an option `:set contentassistmode` which will enable `Ctrl-n`/`Ctrl-p` to go to next/previous match in the Ctrl-Space pop-up.  You can then use `:camap` to remap `<c-n>` and `<c-p>` to `j` and `k` or any other key you want.  I'm sorry but we don't have a solution for the quick-fix pop-up.

See http://vrapper.sourceforge.net/documentation/?topic=configuration#vrapper

**Comment by mmbradle** [comment]
That works perfectly. Thank you so much. 

I remember seeing that mode when reading the documentation but somehow I forgot about it when I actually needed it. This might partially be a result of my not associating the phrase "content-assist", with the ctrl+space command, even though that's the correct phrase.

**Comment by mmbradle** [comment]
I got this working for completion, <kbd>Ctrl</kbd>+<kbd>Space</kbd>, but not for quick-fix <kbd>Ctrl</kbd>+<kbd>1</kbd>. Is this a known issue or is something perhaps wrong in my setup?

**Comment by keforbes** [comment]
I guess you didn't see the part where I said
```
I'm sorry but we don't have a solution for the quick-fix pop-up
```
I don't remember the details but I want to say there was some technical limitation which prevented us from using the same solution in the quick-fix pop-up.
