### ISSUE TITLE
How to install "optional plugins"?

### ISSUE THREAD

**Issue by gustavklopp** [vrapper/vrapper#649]
I didn't get it from the documentation: 
> In addition to the standard Vrapper plugin, we have a couple optional plugins that you can install to further enhance Vrapper's features. 

How do you install the optional plugins? For example, if I want to use the Exchange plugin: If I go to the homepage of the Exchange plugin, they suggest to use Pathogen. Do I need to install Pathogen inside Vrapper?

Thanks!

**Comment by loonies** [comment]
In Eclipse: `Help > Install New Software...`

![vrapper-install-plugin](https://cloud.githubusercontent.com/assets/109212/8148567/323b0744-12a3-11e5-9841-059f489c7b0e.png)

**Comment by gustavklopp** [comment]
Ok! Thanks a lot! (and for the picture with it, it's great)

**Comment by albertdev** [comment]
@loonies 
Can I use that picture and include it in the Vrapper documentation?

**Comment by loonies** [comment]
Sure :)
