### ISSUE TITLE
Relative Line Numbers

### ISSUE THREAD

**Issue by fabiofalci** [vrapper/vrapper#65]
Exactly like this:

http://dlo.me/vim-with-relative-line-numbers/

So, is that possible?

Thanks

**Comment by saamalik** [comment]
@matf this plugin doesn't work anymore--at least in Eclipse Mars

**Comment by saamalik** [comment]
@matf nm i had to uncheck the 'group categorization' checkbox when installing the plugin--because otherwise the plugin doesn't list.

**Comment by snowshoes** [comment]
Until today this plugin works perfectly with Eclipse Mars
