### ISSUE TITLE
ABAP in Eclipse: Exception activating MultiPageEditorPart - Vrapper stops working

### ISSUE THREAD

**Issue by simachri** [vrapper/vrapper#650]
I use the ABAP Development Tools (ADT) from http://scn.sap.com/community/abap/eclipse

ADT make use of multi page editors. When launching Eclipse, Vrapper works fine in the editor tab that is loaded from my previous session. But when I switch editor tabs or editor pages, Vrapper throws an exception:

![multipageeditorpart](https://cloud.githubusercontent.com/assets/3276460/8177556/352d6028-1406-11e5-8cd9-7a8ad9c92ff4.PNG)

This always breaks the search functionality of Vrapper and sometimes even the entire Vrapper functionality. Reloading the current editor tab or editor page as well as switching Vrapper on or off does not help. If I would like to get full Vrapper functionality again, I need to restart Eclipse.

Do you have any suggestions on this, e.g. how I can force Vrapper to reinitialize when switching editor tabs or editor pages?

**Comment by albertdev** [comment]
Looks like a bug...

Can the Eclipse ADT plugins be freely used, and preferably without an SAP install? The website seems to talk about a "[trial version](http://scn.sap.com/docs/DOC-29607)", though I'm not sure if that talks about the server runtime or the plugins. It would be best if I can quickly test some stuff off-line...

**Comment by simachri** [comment]
The ADT plugins can be freely used via the update site https://tools.hana.ondemand.com/luna.

But unfortunately there is no offline mode. A working SAP backend is required in any case as SAP uses a truly server based coding paradigm. I created a clean Eclipse installation, installed the ADT plugins and tried to reproduce the issue, but there is no way to open this specific multi page editor without a SAP backend, even when I create some files locally. The editor always tries to fetch content from the backend first.

I probably will dig into the problem for myself in the near future. Thank you anyhow for the quick response!

**Comment by simachri** [comment]
I created a fix for two issues:

1. vrapper only works on the main page ("Global Class") of an ABAP Class Editor -> Now works on all pages ("Class-Relevant Local Types", "Local Types", "Test Classes", "Macros")
2. Search and replace functionality is not working in the ABAP Class Editor.

The coding (see my fork) definitely needs some cleansing.

Background of the issues:

regarding 1.: The pages of the ABAP Class Editor are loaded lazily. When you switch from the main page "Global Class" to one of the other pages, this very page lacks an interceptor for vrapper. So for each page switch a new interceptor has to be created explicitly.
regarding 2.: The pages of an ABAP Class Editor use a ProjectionViewer to display their contents. The ProjectionViewer is initialized with a document saying "Loading data from backend..." and gets replaced by the actual source code when the download has finished. Vrapper's search and replace functionality is still bound the the first document and needed to bound to the new document with the source code.

**Comment by albertdev** [comment]
@simachri 
Thanks for building a prototype!

I'll have a look at your code and see what we are missing. Now that you have figured out what the problem is I might be able to find another Eclipse project using the same method of editor-building to reproduce these problems locally.

**Comment by albertdev** [comment]
I haven't had time to reproduce this problem.

For now I'm just going to link to your commit so that I don't have to go look for it again: https://github.com/simachri/vrapper/commit/420c2d4481fc81f89507f126f368ef1dbfb698b8

**Comment by albertdev** [comment]
@simachri 
I might have found an alternative fix for the search problem: we could stop caching the `FindReplaceDocumentAdapter` because we shouldn't use its internal state anyhow.

Regarding your fix for that nasty stacktrace: somehow it looks as if your changes wouldn't help the problem unless that stacktrace only happens the second time you switch to a "fresh" editor. Have you noticed any more problems the last few months when running with your modified code?

**Comment by albertdev** [comment]
@simachri 
I still haven't heard back from you if you have found any remaining problems with your custom Vrapper version.

I would like to know because I could then port your fixes to our "master" branch.

**Comment by simachri** [comment]
@albertdev 

Sorry for the late response.

I use my custom Vrapper version almost every day and haven't noticed any issues.

**Comment by albertdev** [comment]
Ok, I pushed my changes.

I still can't reproduce your problem because I have no editor which behaves like yours. You might want to backup your custom version before testing our next unstable release. Please re-open this issue if you find that it won't work.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.61.20151119) which includes this fix.  @simachri, could you try this new build and let us know how it goes?  Thanks!

**Comment by simachri** [comment]
Tested the new unstable build. It works!

Thank you guys!
