### ISSUE TITLE
toggle true into false

### ISSUE THREAD

**Issue by Nymerea** [vrapper/vrapper#651]
Hello

I wonder if you can add feature for toggling true into false and vise versa.

**Comment by igrekster** [comment]
I'm using a similar feature in INSERT mode, but I believe it could be adapted to work in the NORMAL mode as well:
```
au "C/C++ Editor" eclipseaction templcompl org.eclipse.cdt.ui.specific_content_assist.command(org.eclipse.cdt.ui.specific_content_assist.category_id=org.eclipse.cdt.ui.templateProposalCategory)
au "Java Editor"  eclipseaction templcompl org.eclipse.jdt.ui.specific_content_assist.command(org.eclipse.jdt.ui.specific_content_assist.category_id=org.eclipse.jdt.ui.templateProposalCategory)

nnoremap <SPACE>t bel:templcompl<CR>
```
Then define *two* editor templates:
`true` -> `false`
`false` -> `true`
You may want to turn off the auto-insert check box for convenience. After that `<SPACE>t` should do the trick.

**Comment by igrekster** [comment]
A limitation of this solution is that there should be a character after `true` or `false` on the line.

**Comment by albertdev** [comment]
@Nymerea 
Did igrekster's trick work for your use case?

I guess pull requests are welcome if somebody wants to [reimplement switch.vim](https://github.com/AndrewRadev/switch.vim)...

Marked as a Feature Request - maybe we need a label Plugin Request?

**Comment by Nymerea** [comment]
@albertdev sorry didn't understood what said @igrekster so I don't know if it's work.

A plugin request would be great, I would love it !

**Comment by igrekster** [comment]
@Nymerea, if you define two editor templates like this:
![true-false-toggle-1](https://cloud.githubusercontent.com/assets/1772013/11267866/dbb926c2-8f01-11e5-92b9-327c7b8619f3.png)
![true-false-toggle-2](https://cloud.githubusercontent.com/assets/1772013/11267871/df274d20-8f01-11e5-950e-da6fd639a877.png)
And add the commands from https://github.com/vrapper/vrapper/issues/651#issuecomment-112419982, then `<SPACE>` `t` should toggle `true/false`.

**Comment by keforbes** [comment]
I've committed a first attempt at this to see if there's still interest.  I based my implementation on the simplest example I could find for this use case: https://github.com/zef/vim-cycle

Basically, we define an array of replacement strings and `<Ctrl-A>`/`<Ctrl-X>` will replace the word under the cursor with the next/previous word in that list.  By default I defined `yes`/`no`, `true`/`false`, days of the week (`Monday`, `Tuesday`, `...`), and months of the year (`January`, `February`, `...`).  If none of those words are found under the cursor, I defer to the default increment/decrement behavior. 

To define new replacements, `cycle.vim` uses the syntax `call AddCycleGroup(['one', 'two', 'three'])`.  I started out trying to build a base implementation of `call` and registering function names to it but I don't think there will be too many users for this and I'd only be faking out the `call` behavior anyway.  So I made it simple for myself, just space-delimited words.
`:AddCycleGroup foo bar baz`

My implementation doesn't allow for multiple-word replacements anyway so I wouldn't want to use quotes and make you think any quoted string would work.

I'll let you know when I've updated the unstable update site so you guys can try it out ( @igrekster , @Nymerea ) if either of you still care.

**Comment by keforbes** [comment]
Ok, I've updated the unstable update site with a new build (0.67.20160516) which includes this new "cycle" optional plugin.  Please give it a try and let me know if you think it's worthwhile.

**Comment by keforbes** [comment]
Ok, so it seems no one cares about this anymore... I guess I might as well keep it though since it does function.

**Comment by Nymerea** [comment]
No no, I still care ! Right now I'm more in documentation writing phase than developping phase.

But ASAP I came back to dev (hopefully soon) I'll try you'r solution !

**Comment by keforbes** [comment]
Good, I'm glad you still care. :smile:  I'll give you a little more information then just to be safe.

As with any Ctrl key combo, you have to unbind it from Eclipse before Vrapper can receive it.  This means you'll need to Unbind `Ctrl+X` and `Ctrl+A` from Eclipse in order to use this feature.  Also, it uses the same "grab word under cursor" logic as `*` and `#`, which means its behavior is defined by the `iskeyword` setting in case you want to tweak the `word` logic.  Since I'm using this `word` logic, I don't have any plans to support multi-word replacements.

I was originally testing this with a cycle of `if`->`else if`->`else` but when `if` turned into `else if` the word under the cursor was `else` so it changed the `else` to `if` and I ended up with `if if`.  That's why I only support replacing single words.

**Comment by Nymerea** [comment]
Is there a way to change the shortcut ? Because I use a lot CTRL+A, CTRL+C, CTRL+V (much more efficase for copy/cut/past stuff than the vim way)

**Comment by albertdev** [comment]
@Nymerea 
If you know that some shortcut is free then you can use `nnoremap` to tell Vrapper to listen to it.

Example: `:nnoremap <S-F4> <C-A>` and then `:nnoremap <C-S-F4> <C-X>` will make Vrapper listen for `Shift` + `F4`, same with the other shortcut except that uses `Ctrl` + `Shift` + `F4`.

**Comment by keforbes** [comment]
You can map it to any other key too, it doesn't have to involve `Ctrl`.

```
nmap ga <C-A>
nmap gx <C-X>
```

**Comment by keforbes** [comment]
Also, just in case you've never remapped keys in vim before, we're referring to the `.vrapperrc` file used for configuration.
http://vrapper.sourceforge.net/documentation/?topic=configuration#config

**Comment by loonies** [comment]
Is it possible to keep caret position at the beginning of a word every
time? Right now if caret position is on the first letter it stays there,
but if in the middle of a word it will move past word if there is a
special character placed right after. This will prevent any
further cycling.

Consider those examples:

    opts = ['True', 'False']

    while True:
        print('Hello world!')

If caret position is on `T` in `'True'` it will cycle to `'False'`. This
is cool. However if, caret is on any of `rue` in `True`, it will move to
the second quotation mark `'` in `'True'`, preventing you from cycling
further. The same with `while True:` example, it will move to `:` if
caret is in the middle of the `True` word.

**Comment by loonies** [comment]
Workaround

```
nnoremap <C-A> <C-A>T<Space>
nnoremap <C-X> <C-X>T<Space>
```

:smile:

**Comment by keforbes** [comment]
@loonies, I've updated the unstable update site with a new build (0.69.20160613) which will always move the cursor to the beginning of the word for the next cycle.  You shouldn't need your workaround anymore.

**Comment by loonies** [comment]
There are some cases where it doesn't work as expected.

`[]` is the cursor position.

Given those mappings:

    AddCycleGroup Yes No
    AddCycleGroup YES NO
    AddCycleGroup True False
    AddCycleGroup TRUE FALSE
    AddCycleGroup on off
    AddCycleGroup On Off
    AddCycleGroup ON OFF
    AddCycleGroup && ||
    AddCycleGroup and or
    AddCycleGroup AND OR
    AddCycleGroup == !=
    AddCycleGroup === !==
    AddCycleGroup if elif else

Python (PyDev) editor the _word_ based cycles (Yes, No, YES, NO, etc.)
are working while _sign_ based are not (&&, ||, ==, !=, etc.).

Example

    if op [=]= 'a':
        res = calc.add(nu)

Pressing `C-A` or `C-X` does nothing.

The same behavior is observed in PHP (PDT) editor, with one caveat.
Inside of brackets it behaves differently.

Given this example:

    if ($foo [=]= TRUE) {
    }

Pressing `C-A` or `C-X` will produce:

    if (FALSE == TRUE) {
    }

**Comment by keforbes** [comment]
Hmm, I'm not sure what I can do about that.  This feature uses the same regex as `*` and `#` for "grab current word under cursor", which is defined by the `iskeyword` setting (default to `a-zA-Z0-9_`).  So it won't really work on "words" that don't have any "word characters".  This is to handle the scenario where you have a word surrounded by non-word characters (like `("true")`).  It's possible you could try adding `&`, `=`, and `!` to your `iskeyword` regex (`set isk+=&=!`) so they're treated as word characters, but that means if you have a line without spaces (`foo=bar`) it would treat that as one word.
