### ISSUE TITLE
set noexpandtab

### ISSUE THREAD

**Issue by skybber** [vrapper/vrapper#654]
I have 'set noexpandtab' in the .vrapperrc for months and never  had problem with it. But after last eclipse update it stopped working. If I set noexpandtab manually from vrapper cmdline it works again but not the default setting in vrapperc.

**Comment by albertdev** [comment]
You are talking about "last eclipse update", do you mean a new Vrapper release or some update from the Eclipse project?

What is the behaviour for inserting a literal Tab in insert mode compared to doing a `>>` or `==` operation? Are there any Vrapper errors in the log files by any chance?

**Comment by skybber** [comment]
I have eclipse 4.4.2 and vrapper 0.56.0, but the problem was already in 0.56.0. I'm 100% sure it works before I've installed dbeaver plugin. If I uninstall dbeaver the problem still persists.

**Comment by skybber** [comment]
It was my problem. I have pretty long .vrapperrc and lost expandtab setting after noexpandtab. I'm sorry ...
