### ISSUE TITLE
Mode and recording status do not respect Eclipse theme

### ISSUE THREAD

**Issue by mario-grgic** [vrapper/vrapper#658]
It appears that status mode and macro recording use SWT CLabel to render the message. Unfortunately, even though they set the foreground and background color of the parent, they do not get updated when Eclipse theme is changed. 

I use "Jeeeyul's Themes" Eclipse extension ( https://github.com/jeeeyul/eclipse-themes  ) that fixes too broad spacing between eclipse elements and comes with a bunch of nice looking color themes, but vrapper's mode status looks completely out of theme.

**Comment by albertdev** [comment]
Would you be so kind to attach a few screenshots of how Vrapper looks on your machine?

What Eclipse and Vrapper version are you running?

**Comment by mario-grgic** [comment]
This is a problem with Eclipse 4.3 Luna and Eclipse 4.5 Mars on both Mac OS X and Windows 7 (have not tried earlier versions). 

Yes I have restarted Eclipse multiple times and changed to various other themes. Only themes that use gray backgrounds make the status bar "blend in".

Here are the screenshots with Eclipse 4.5 Mars on OS X and Window 7


![eclipse 4 5 mars mac os x](https://cloud.githubusercontent.com/assets/1044216/8379949/3202dd68-1bf1-11e5-8291-6d55126380a0.jpg)
![eclipse 4 5 mars windows 7](https://cloud.githubusercontent.com/assets/1044216/8379950/34e505a6-1bf1-11e5-94ec-8edc60c15173.jpg)

**Comment by albertdev** [comment]
Thanks for your feedback and screenshots.

I'm going to mark this as "Annoyance" for now as it's not breaking anything, but rest assured that this issue will be kept open to be looked at.

**Comment by albertdev** [comment]
As it happens it actually took removing code to fix this. The code had used some old widgets in the past which needed their text and background color, and I replaced it with a `CLabel` to have better font styling. It seems though that if you don't set any styling, Eclipse will happily inherit it from the parent and hence update it if you change the theme.

This fix will be included in the next unstable and 0.58 release build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.57.20150702) which includes this fix.  Please give it a try and let us know if you run into any problems.  Thanks!

**Comment by mario-grgic** [comment]
No problems, everything is working well. Thank you very much.
