### ISSUE TITLE
Commands requires exactly one space to pass arguments

### ISSUE THREAD

**Issue by DoumanAsh** [vrapper/vrapper#666]
* Working case:
```
:e [file]
```

* Not-working with several spaces(and no tab-completion):
```
:e                [file]
```

Hm... github hides several spaces for some reason.
Anyway to reproduce:
enter command and several spaces. After that try to pass argument

**Comment by aVolpe** [comment]
Use markdown

* Working:
```
:e [file]
````
* Not working
```
:e  [file]
````

**Comment by DoumanAsh** [comment]
What you were using. I rarely use markdown on github so would appreciate if you could tell what's type of markdown did you use?

**Comment by aVolpe** [comment]
See [this](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), basically I use the __```__ syntax.

**Comment by DoumanAsh** [comment]
Oh... i used code quote but it seems it work differently when you put it onto one line
Thanks

**Comment by albertdev** [comment]
Indeed, it's odd that multiple spaces aren't normalized to single ones. I've marked this as a defect.

**Comment by solde9** [comment]
I've created several Patterns and a Matcher in `CommandLineParser` so we
can match the command with one or more spaces. This fix the problem with
tab-completion of the file. Is this approach ok? I'm leaving a reference to the commit.

**Comment by albertdev** [comment]
@solde9 
While I don't quite like adding lots of regex to the parsing code, some quick testing prove your code works. I will add it to master so that this feature can be tested through the unstable update site.

Many thanks for looking at this issue, and sorry for "leaving you hanging".

@DoumanAsh 
This fix will be included in the next unstable / release build.

**Comment by solde9** [comment]
@albertdev Thanks! 
I had a feeling that the solution was not the best, so I did not insist too much on the matter. I am glad that it can be included, at least until a more appropriate and maintainable implementation is found.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.61.20151020) which includes this fix.  Go ahead and give it a try!
