### ISSUE TITLE
Search match highlight  and  :noh performance

### ISSUE THREAD

**Issue by mario-grgic** [vrapper/vrapper#667]
This is with Eclipse 4.5 Mars 64bit on Windows 7 and Mac OS X 10.9.5 and Vrapper Unstable 0.57.20150702. Highlighting of search results (I have incremental search option in .vrapperrc, but I don't think it makes a difference) and un-highlighting of search results with `:noh` is rather slow, so much so that you can watch Eclipse do them one by one on a page with 5 - 6 search matches. This is also on a relatively fast hardware (dual CPU, 8 core system with 32 GB of RAM and 8GB Eclipse heap).

**Comment by albertdev** [comment]
I'm not sure yet whether we can resolve this; Vrapper finds all matches within seconds and tells Eclipse to highlight those bits of text.

It's then up to Eclipse to repaint the editor, and for some reason this happens one by one. I did a quick experiment with locking view buffering, but this doesn't resolve anything as it's really offloaded.

I'm going to mark this as an annoyance and "Blocked by Eclipse" to signal that this needs further research. A quick check on Google made me aware of an `IAnnotationModelExtension` API which might allow batch operations on annotations, no clue whether it would be faster.

**Comment by mario-grgic** [comment]
I took a quick look at how VI Plugin (http://www.viplugin.com/viplugin.htm) does highlighting (it does it almost instantly) and it has something like this:

```
EditorImplementation.java


   public void highlightSearchRegions(final Vector<Region> regions) {
       this.lastSearchHighlightingRegions = regions;
       for (int i = 0; i < regions.size(); ++i) {
           Region region = regions.get(i);
           this.foldingExtension.exposeModelRegion(region.getOffset(), 1);
           region = this.foldingExtension.model2viewRegion(region);
           if (region != null) {
               final StyleRange style = new StyleRange(region.getOffset(), region.getLength(), 
                              PreferenceHelper.getColor("foreground_highlighting"),          
                              PreferenceHelper.getColor("background_highlighting"));
               this.styledText.setStyleRange(style);
           }
       }
   }
```

i.e. it seems to use StyleRange to quickly highlight precomputed search matches (Regions are just start/end (offset) positions).

I don't know if any of this is applicable to Vrapper (the code here is doing something completely different and seems to use Annotations for highlighting).

**Comment by albertdev** [comment]
Is tha bit of code open-source and GPL-compatible? If not, you'd better remove and explain the gist of it. I don't want us to get into some copyright trouble, so it's better to follow the [Chinese wall](https://en.wikipedia.org/wiki/Chinese_wall#Computer_science) method.

**Comment by mario-grgic** [comment]
VI plugin used to be open source under Common Public License (no idea if this is compatible with GPL or not), and ancient version of it from 2004 is still available at 

http://sourceforge.net/projects/viplugin/files/viplugin/

The plugin author has decided to go close source in the meantime, but he still ships the source code inside the jars (at least he did until a few versions ago). 

In any case, it looks like calling setStyleRange with StyleRange object constructed out of regions of text (start/end position) is much faster.

**Comment by albertdev** [comment]
I've taken a look at `StyleRange`, but it needs raw `Color` instances which I would need to pull from some configuration screen.

Since our current annotation code doesn't need any extra configuration screen, I went ahead using `IAnnotationModelExtension` in some prototype code. Highlights are now instantaneous when matching every char in a 10kB file, so I think annotations should work fine too.

**Comment by mario-grgic** [comment]
This is fantastic. Looking forward to trying out the changes and testing things :D.

**Comment by albertdev** [comment]
This will be included in the next unstable and release build.

Be aware though that I changed the highlighting configuration: I noticed that we had some ambiguous setting IDs which would clash, so if you customized the highlighting (annotation) colors you might have to do it again.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.57.20150713) which includes this fix.  @mario-grgic please install this build and let us know if it resolves your problem.  Thanks!

**Comment by mario-grgic** [comment]
Everything is working as expected. Performance now is fantastic. Thank you.
