### ISSUE TITLE
inoremap map jj to <Esc> not work in some conditions

### ISSUE THREAD

**Issue by idealvin** [vrapper/vrapper#669]
See my vrapperrc file:
```cpp
  inoremap c<tab> class<space>
  inoremap jj <Esc>
```

When I type `cjj`, the `jj` dose not map to \<Esc\>,  
and if I type `cjjj`, it results in `cj` and turns to normal mode from insert mode.  
There is no problem in vim with the same configs. So maybe something is wrong with vrapper. Please pay attention to it!

**Comment by idealvin** [comment]
I have solved it by myself.  See https://github.com/idealvin/vrapper

**Comment by albertdev** [comment]
I implemented general backtracking in the remapping logic. Command line mode and insert mode should now properly retry any mappings which they didn't pick up the first time.

This fix will be included in the next unstable and release build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.61.20151115) which includes this fix.  Please give it a try and let us know if you're still seeing any issues.  Thanks!
