### ISSUE TITLE
Fix indentation action "=" broken on Eclipse-Mars

### ISSUE THREAD

**Issue by robbadler** [vrapper/vrapper#671]
Upgrading from Luna to Mars, vrapper no longer reacts to "==" while in system mode to fix line indentation.

**Comment by albertdev** [comment]
What kind of files are you editing? Have you installed the Vrapper JDT enchantments (these might not be included when installing from Marketplace)?

Can you post a screenshot after running `:set list` to show what's broken?

**Comment by robbadler** [comment]
Yikes. I hadn't gotten CDT specific plugin installed. Egg on my face.
Thank you for the quick help.

**Comment by albertdev** [comment]
You're welcome.

I'm going to close this issue then, sorry that we haven't found a way yet to bring in the CDT stuff automatically.
