### ISSUE TITLE
Visual mode for keyboard selection

### ISSUE THREAD

**Issue by mmbradle** [vrapper/vrapper#674]
## Summary:
Support moving into visual mode when making Eclipse selections with the keyboard.

## Info:
When I select text in Eclipse with a shortcut, Vrapper does not go into Visual mode. For example if I use the keyboard shortcut <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>&uarr;</kbd>, I will have text selected but not be in Visual mode. If not everyone wanted this behavior I would suggest adding a `:set visualkeyboard` option for those that did.

## Use cases:
- <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>&uarr;,&darr;,&larr;,&rarr;</kbd> (expand/reduce selection)
- <kbd>Ctrl</kbd>+<kbd>.</kbd> (jump to next occurrence - useful for errors/warnings )
- <kbd>Ctrl</kbd>+<kbd>k</kbd> (incremental search)

## Work-around
For anyone else having this save issue, hitting <kbd>v</kbd> will move you into visual mode without changing the selection. You can see if you are in visual mode or not by looking down at the status bar.

As always, thanks to creators/maintainers of this plugin. Great stuff here!

**Comment by albertdev** [comment]
Huh, would you look at that... In the past, pressing <kbd>v</kbd> would actually reset any selection you made in normal mode. I must have somehow accidentally improved the situation. Once you are in Visual mode the selection changes should work OK.

I'm painfully aware of this issue though, and I think this is a duplicate of #511 and #17.

I was working on an experimental fix in pull request #519 though it didn't work out so well back then, maybe I should rebase it and try it with the current selection code...

**Comment by mmbradle** [comment]
Yes, I see that it is a duplicate. Sorry, I tried to search for it in case it was, but I missed those.
I'm glad <kbd>v</kbd> doesn't reset the selection though! Good job there :)
