### ISSUE TITLE
Allow termination of macros and mappings via <C-c>

### ISSUE THREAD

**Issue by McBrainy** [vrapper/vrapper#678]
Adding the ability to use control-c to terminate mappings and macros would be a partial fix for #509. Vim does it, and it was the first thing I tried when I triggered the infinite macro recursion bug today.

**Comment by albertdev** [comment]
I'm afraid this is currently not possible to implement.

Vrapper supports "nested macros" but it was never built for recursive execution. This means that all macro execution happens in a single thread and as fast as possible, with no pause to check if keys have been pressed.

Then there's also the fact that Eclipse has its own key binding framework which you are not supposed to circumvent, so Eclipse would keep trying to execute the "Copy" action for most people.

How often do you use such macros or mappings? Would it be acceptable to propose a cop-out by using the `:vim` command and switching to Vim itself?

**Comment by McBrainy** [comment]
Didn't know about the :vim command. I guess I've tried to use them twice in the past week, although I don't usually use them that often, and one of those times I did switch to vim. And I forgot about the copy binding on most OSes, although that's not the biggest issue, since it could be mapped to something else. I suppose :vim is an acceptable alternative, though.

**Comment by albertdev** [comment]
I'm going to close this feature request because I think we're just missing too much to get it fixed like I explained in #509.

I have tagged it as "Rejected" though so that it can be found again should someone help with improving our motion code.
