### ISSUE TITLE
how can i use this plugin for netbeans?

### ISSUE THREAD

**Issue by xibeilin** [vrapper/vrapper#681]
i found jVi, but it's not suitable !

**Comment by albertdev** [comment]
I'm afraid that you can't.

As you can read on [the Vrapper Homepage](http://vrapper.sourceforge.net/home/), we're developing an Eclipse plugin. While pieces of Vrapper Core would be reusable, the entire editor integration would need to be redeveloped for Netbeans.

Have you tried [contacting the jVi team](http://sourceforge.net/projects/jvi/support?source=navbar)?
What kind of things do you miss?

**Comment by xibeilin** [comment]
thanks for your answer.

I just found jVi can configure. i missed.

There is a configuration page in jVi config.
