### ISSUE TITLE
[no]wrapscan or anything like it?

### ISSUE THREAD

**Issue by klandingham** [vrapper/vrapper#684]
I can't find :set nowrapscan anywhere in the documentation.  Is this implemented?  If not, any plans to do so, or anything equivalent?

Search wrapping is one "feature" of Vim I never liked.  I want to know when I've reached the last occurrence of what I am looking for without having to visually figure out that the search has wrapped.

**Comment by keforbes** [comment]
No, that feature was not implemented.  Fortunately, it was a simple enough fix that I was able to implement it in the half-hour I had available.  Of course, with that said, let me know if I screwed something up.

I've updated the unstable update site with a new build (0.59.20150917) which includes this fix.  Please give it a try and let me know how it goes.  Thanks!

**Comment by klandingham** [comment]
Hi,  thank you for replying.That sounds great.  Unfortunately, because of the environment in which I am using Vrapper, I'm afraid I can't test it for you right away.It takes months to get a version upgrade approved.  I've started the process, but I'm sorry that I can't give you the quick feedback you asked for....maybe I'll try to set something up at home...if so I'll definitely test it and let you know.Thanks again.   On 09/17/15, keforbes<notifications@github.com> wrote: No, that feature was not implemented.  Fortunately, it was a simple enough fix that I was able to implement it in the half-hour I had available.  Of course, with that said, let me know if I screwed something up.I've updated the unstable update site with a new build (0.59.20150917) which includes this fix.  Please give it a try and let me know how it goes.  Thanks!—Reply to this email directly or view it on GitHub.

**Comment by klandingham** [comment]
Hello,I tried the wrapscan setting in my unrestricted environment (Luna) and it works perfectly.Any idea when it might get into a real release?  I have to put all software (including updates) through an approval process, which takes a while.  I doubt if I will be able to get anything labelled "unstable" through that process.Thanks very much.  On 09/17/15, keforbes<notifications@github.com> wrote: No, that feature was not implemented.  Fortunately, it was a simple enough fix that I was able to implement it in the half-hour I had available.  Of course, with that said, let me know if I screwed something up.I've updated the unstable update site with a new build (0.59.20150917) which includes this fix.  Please give it a try and let me know how it goes.  Thanks!—Reply to this email directly or view it on GitHub.

**Comment by keforbes** [comment]
I try to do a stable release every other month, which means the next release will be in about two weeks.  I'll update this defect when that release is out.

**Comment by keforbes** [comment]
@klandingham, I've released stable version 0.60.0 which includes `wrapscan`.  You can request an approval from your company now. :smile:

**Comment by klandingham** [comment]
Thanks for letting me know.  Cheers.   On 10/04/15, keforbes<notifications@github.com> wrote: @klandingham, I've released stable version 0.60.0 which includes wrapscan.  You can request an approval from your company now.  —Reply to this email directly or view it on GitHub.
