### ISSUE TITLE
The Content Assist popup auto show when move cursor in normal mode

### ISSUE THREAD

**Issue by sanwv** [vrapper/vrapper#685]
I set auto activation delay in 0 msecs,in normal mode the content assist popup menu will auto show, can I close the it?or not show in normal mode?

**Comment by albertdev** [comment]
First of all sorry that we didn't get back to you any sooner. We try to answer cases one by one but this issue must have been forgotten about.

I just checked my preferences to see what setting you are talking about but it seems I have the same setting?

![content_assist_settings](https://cloud.githubusercontent.com/assets/1451362/10417317/829de412-7037-11e5-95dc-9b5430cbfad7.PNG)

Can you explain what you do and what happens from the time you open a fresh editor in Eclipse until the popup opens?

**Comment by sanwv** [comment]
auto triggers for java '.abcdefghijklmnopqrstyvwsyz' 

esc can dismiss popup but when move cursor will show again.

orther tab or c-n/c-p key if can cycle itemes?

😜

**Comment by albertdev** [comment]
I don't quite get what you're saying. In normal mode I don't get the popup automatically, even when I change the "Auto activation triggers for Java" to all printable characters.

Could you make a video of your Eclipse or something? Maybe using https://screentogif.codeplex.com/ ?

**Comment by keforbes** [comment]
His problem is that he set his activation delay to 0ms, which means the content assist pop-up appears after every key press.  That pop-up is still appearing when he presses a button in normal mode.

**Comment by keforbes** [comment]
Oh, nevermind.  I see in your screenshot you have it set to 0ms too.  Weird.

**Comment by sanwv** [comment]
i will make a video soon

**Comment by sanwv** [comment]
I recently upgraded eclipse to 4.5, the problem goes away😖

**Comment by keforbes** [comment]
I'm glad it's working for you now!  Can we close this issue?

**Comment by sanwv** [comment]
yes，thanks

**Comment by albertdev** [comment]
Thanks for the update. Case closed.
