### ISSUE TITLE
Vrapper not working on mars installation

### ISSUE THREAD

**Issue by chessami92** [vrapper/vrapper#690]
Just did a clean install of mars (v4.5.1) and I do not even see the vim icon in my toolbar and there is nothing in my error log on startup.

**Comment by albertdev** [comment]
I'm sorry to hear that.

Can you show a screenshot of which Vrapper plugins you have installed?

Go to Help > About Eclipse, then in that window click the Installation Details button. On the new window, go to the Plug-ins tab and enter "vrapper" in the filter box.

**Comment by albertdev** [comment]
Also, did you install from the marketplace or from our [Eclipse update site](http://vrapper.sourceforge.net/update-site/stable)?

**Comment by chessami92** [comment]
I originally installed from the marketplace and then uninstalled and tried from the update site. Unstable seems to behave the same. Vrapper actually shows up under "Installed Software" instead of "Plugins." Could that be an issue?

![image](https://cloud.githubusercontent.com/assets/2281967/10417370/7f485c54-6ffe-11e5-9a4e-6ca85d31f754.png)

![image](https://cloud.githubusercontent.com/assets/2281967/10417378/8f418338-6ffe-11e5-8158-4e411e5aca78.png)

**Comment by albertdev** [comment]
That... is very odd and bad indeed.

Can you try uninstalling Vrapper by using the Installed Software screen, checking if any trace of it remains in your setup and then install it once more from the stable update site?

**Comment by albertdev** [comment]
@chessami92 
Any luck in recovering your installation? I'm afraid I can't do much until we find what would even cause your installation to get corrupted in such a way.

**Comment by albertdev** [comment]
@chessami92 
Any news? Did you restart your Eclipse installation after Vrapper was installed?

**Comment by chessami92** [comment]
Hey @albertdev thanks for following up on this. It's not my usual development machine so I will try some things out tonight.

**Comment by smalers** [comment]
I have the same issue.  I installed a clean Mars Java EE 64-bit on Windows 7.  I noticed Vrapper and thought I would try it.  I did the Marketplace install first, including the required Eclipse restart. The Vim button does not show up.  The software shows up under Installed Software similar to chessami92's images (not listed under Plug-ins).  I uninstalled.  Then I installed using the http://vrapper.sourceforge.net/update-site/stable link using Install New Software.  Restarted.  Still no Vim button.  In general I find it frustrating that it is difficult to know where Eclipse plug-ins install (under eclipse?, under workspace?, under user files?).  It is therefore difficult for me to check where files do or don't exist.  Any guidance on this would be appreciated and might help resolve the issue.

**Comment by muellan** [comment]
Just to add some info: I am using Vrapper with a 64-bit Eclipse Mars without problems on Windows 10 (64bit).
I did a clean install of Eclipse after Mars was released and added all my plugins (all using their update sites) including Vrapper after that. No problems.

**Comment by lvqiang** [comment]
I have the same problem. and don't know how to fix it...

**Comment by albertdev** [comment]
@smalers @lvqiang If you're running Windows, open an explorer window of your Eclipse installation directory.

The `plugins` directory should contain files whose names start with `net.sourceforge.vrapper.`. If they're not there then Eclipse already failed to download them. If they do exist we'll have to check the `features` directory which should also contain files with `net.sourceforge.vrapper.` in the filename.

**Comment by chessami92** [comment]
I re-installed eclipse in C:\eclipse instead of C:\Program Files\eclipse and installed vrapper and it seems to be working now.

**Comment by albertdev** [comment]
@smalers @lvqiang
I did not consider the "Program Files" directory before but it seems Eclipse may have different behavior due to UAC when installing into that folder. Would it be possible to check a new installation of Eclipse in another folder or checking if you can create a `.eclipse` folder in `C:\Users\<username>`?

**Comment by keforbes** [comment]
I'm closing this issue.  The person who filed it was able to resolve their problem.  I tried installing Eclipse into `C:\Program Files` myself and Vrapper installed fine so I'm not sure what caused the issue.
