### ISSUE TITLE
Paste to command-line is not working

### ISSUE THREAD

**Issue by yelmu** [vrapper/vrapper#693]
If you try to paste text to command-line (:) with e.g. Shift+Insert or Ctrl+C, text is pasted to editor instead of command-line.

Steps to reprocude:
1. Copy some text to clipboard
2. Enter command mode (:)
3. Paste clipboard contents
4. Text is inserted to editor instead of command line

**Comment by albertdev** [comment]
This is a duplicate of #174 and is sadly a known issue. (BTW: Did you mean `Ctrl+V`?)

Another way to use paste is to use `Ctrl+R` and then `+`, or to Right-click on the command line and then clicking Paste from the context menu.

**Comment by yelmu** [comment]
Right, I meant Ctrl+V.  `Ctrl+R` and `+` seems to work, no need to use mouse :smile:  Thanks!

I think, this can be closed as duplicate of #174 .
