### ISSUE TITLE
Editor loses focus after closing split window

### ISSUE THREAD

**Issue by loonies** [vrapper/vrapper#699]
If you close a split window the editor loses focus. You have to click on
the editor to make it active again. No Vrapper command works in this
case, neither Eclipse view (`CTRL + F7`) or editor (`CTRL + F6`)
swithcer. Eclipse menu actions are working (`ALT + <key>`) though.

**Comment by albertdev** [comment]
Are you sure this is Vrapper's fault? I think this might be a duplicate of #435 where I noticed that Eclipse sometimes has the same behaviour.

I don't like to meddle with the whole Eclipse environment when we're actually being shut down.

**Comment by loonies** [comment]
Sorry missed that issue. It is duplicate.

**Comment by albertdev** [comment]
No problem.

You're welcome to contribute any new info you can find, I haven't found anything new.
