### ISSUE TITLE
Search-on-typing and hlsearch

### ISSUE THREAD

**Issue by ZhekaS** [vrapper/vrapper#706]
Feature request:
Jump to the first match as the search pattern is typed.
Highlight the matching text if `:hlsearch`.

**Comment by albertdev** [comment]
Can you run the command `:set hlsearch` and search again?

I'm wondering in what way our existing feature differs from what you're asking so maybe you might want to add an example.

**Comment by ZhekaS** [comment]
Sorry, disregard the part about `hlsearch`, it looks like I've misused it.

**Comment by keforbes** [comment]
Can you just enable `incsearch`?

**Comment by ZhekaS** [comment]
Oh. Feeling dumb now. It is enabled by default in Vim, so never realized it can be turned on/off. Thank you, it can be closed now..
