### ISSUE TITLE
"Wrong number of hints passed to search mode" while at blank line EOF

### ISSUE THREAD

**Issue by ZhekaS** [vrapper/vrapper#707]
Steps:
1) Create a file with some text
2) Add an empty line in the end of the file (just a newline)
3) In normal mode position the cursor at the end-of-file (the empty line)
4) Try searching some text

Result:
 1) "Wrong number of hints passed to search mode!" error is displayed
 2)  The editor does not respond to any keyboard commands until Vrapper toggled off and on

**Comment by albertdev** [comment]
Interesting find... Marked as a defect.

**Comment by albertdev** [comment]
Ah, found it: it's a combination of suppressed exceptions making the cause unclear as well as an out-of-bounds problem in search mode. I'll do some more tests first.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.63.20160104) which includes this fix.  Good find!
