### ISSUE TITLE
Edit window not refreshing while navigating through hyperlinks in call stack of exception

### ISSUE THREAD

**Issue by hamxyy** [vrapper/vrapper#711]
When an exception happens, eclipse will print a call stack in the console with hyperlinks pointing to the lines of code where the exception occurs. If the user clicks on the link, the editor will jump to the exact line of the corresponding code file. But after installing vrapper, this functionality still works, but immediately after clicking on the hyperlink, the editor is not refreshed until the user activates the editor window.
This is not a severe bug, I would classify it as a "UI bug", however it's pretty annoying because normally users quickly scan through the locations where the exceptions occurs, if there is no immediate refreshing in the code area, it's not only misleading but also troublesome.

//First time submitting issues, not sure whether the style is followed properly, let me know if it's not.

**Comment by albertdev** [comment]
Could you tell me what Eclipse version you're running and on what OS / desktop environment? Does it work when you disable Vrapper using the toggle button in the toolbar? I take it this is a Java stacktrace and hence you're using the Java Development Tools?

Also, don't worry too much about the style, we're pretty informal about it.

**Comment by albertdev** [comment]
It seems this is a more benign version of #717: clicking the stacktrace will register a selection which will in turn causes Vrapper to enter a redraw loop where the editor won't get the chance to paint itself completely.

Clicking in the editor clears the selection and the redraw loop stops.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.63.20160123) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!
