### ISSUE TITLE
Request support for sentence text object

### ISSUE THREAD

**Issue by letientai299** [vrapper/vrapper#715]
I find it surprisingly that vrapper doesn't support `is` and `as` text object, while it work nice with paragraph text object `ip` and `ap`.

**Comment by albertdev** [comment]
I guess nobody ever asked for it.

I will happily mark this as a feature request but I'm afraid we're seriously short-staffed at the moment. Pull requests are welcome.

**Comment by keforbes** [comment]
We already have a SentenceMotion class but it's mapped to `(` and `)`.  I wonder how much extra work it would take to add support for sentence text objects.  I don't have the code in front of me right now so I don't know how the paragraph motion `{` and `}` differ from the text object `ip` and `ap`.
