### ISSUE TITLE
tab expands to spaces no matter what settings i use

### ISSUE THREAD

**Issue by andrei-pokrovsky** [vrapper/vrapper#722]
It seems i tried all combinations of expandtab and built-in eclipse editor settings but tabs expand to spaces no matter what! Here's my ~/.vrapperrc file:

set nosmartindent
set noautoindent
set shiftwidth=4
set tabstop=4
set noexpandtab
set ignorecase
set smartcase
set hlsearch
set softtabstop=4

My editor is set to no expand tabs and when i type :set et? i get false.

Any suggestions?

I'm using vrapper 0.64 and NSight Eclipse Edition 7.0.

Thanks!!!

**Comment by AaronM04** [comment]
I'm new to vrapper, but I think maybe the .vrapperrc does not control tabs vs. spaces.

Instead, go to Code Style -> Formatter in Preferences, and edit your profile. It will be on the Indentation tab.

Let me know whether it works.

**Comment by albertdev** [comment]
Always check your Eclipse formatting settings first as they decide what happens when you press `<Tab>` or let Eclipse do a reformat.

The newest versions of Vrapper should then auto-detect your settings if you *haven't* set them in your `.vrapperrc`.

**Comment by AlanDThiessen** [comment]
I just had the opposite experience with Vrapper 0.64.0 on Eclipse 4.4.2.M20150204-1700 in Windows.  Vrapper and Eclipse are both configured to expand tabs.  However, Vrapper was inserting tabs.  Eclipse CDT was inserting spaces when Vrapper was disabled.

It appears Vrapper is using context of the preceding lines to determine whether or not to insert spaces or tab.  This is irregardless of the settings in either .vrapperrc or _vrapperrc in my home (Users) directory.  If the preceding lines use tabs, it uses tabs.  If the preceding lines use spaces, it uses spaces.  I saw both behaviors in the same edit session on the same file.

**Comment by andrei-pokrovsky** [comment]
>>I'm new to vrapper, but I think maybe the .vrapperrc does not control tabs vs. spaces.
>>Instead, go to Code Style -> Formatter in Preferences, and edit your profile. It will be on the indentation tab.
>>Let me know whether it works.

That worked, thank you!!
