### ISSUE TITLE
Surrounding a visual selection with a tag doesn't surround the selection

### ISSUE THREAD

**Issue by jccyr01** [vrapper/vrapper#726]
Hi, 

When using the surround plugin, surrounding a visual selection with a tag, causes the start and end tags to be inserted before the selected text instead of surrounding it.

```html
<div>
    example text
</div>
```

1. Select the word "text".
1. Type `Stspan<CR>`

You end up with:
```html
<div>
   example <span></span>text
</div>
```

I have been debugging the code and the selection is being cleared before the insertion of the tag, when you exit command mode (where you type in the tag).

Note that surrounding with a tag works correctly when typing `ysiwtspan<CR>` and that surrounding with quotes or brackets works in visual mode.

**Comment by albertdev** [comment]
Thanks for reporting this problem. I can reproduce it in a unit test, this likely has existed for a while without anyone noticing.

The problem appears to be that the command line mode where you type in the tag returns to visual mode when it shouldn't - by that point we know what "insert delimiter" command to execute and hence we should immediately move to Normal mode. I'll take a look later today.

**Comment by albertdev** [comment]
This fix will be included in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.65.20160225) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!

**Comment by jccyr01** [comment]
The unstable build works. Thanks for resolving this issue quickly.
