### ISSUE TITLE
Searching in selection, and search atoms

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#729]
Searching in selection is a handy thing. Right now, search and replace inside a selection is easy, but search only is not, at least as far as I'm aware. There are a couple of ways to approach this. One would be to add an option that, when visual mode is active, / simply hooks into Eclipse's search only in the highlighted area. I say that this should be an option, because if you do this, you lose the ability to extend the search area by finding words. This option could also be enabled for regular visual and line visual mode independently.

Another interesting way to go would be to add a couple of the search atoms. For instance, \%V searches in the previous visual selection. If this were added, then you would be able to type this manually and use it with no modifications. Or if you use it often, you could a shortcut key mapped to <Esc>/\%V; then when in visual mode you would hit this shortcut key and it would automatically dump you into a search that would only be over the previously selected area.

**Comment by albertdev** [comment]
Could this be related to #637?

We can always clip the "next search result" offset to just the ones included in the selection, it's all in getting the parsing and logic code correct.

**Comment by quicknir** [comment]
It is related, indeed, though what they want is to add the %V atom to search and replace which would allow search and replace more precisely than line by line (which already works). When it comes to just searching, your options are worse because it is not a line command unlike replace. So you cannot even search within a range of lines right now.

Adding the %V atom for both (which might be heavily related, and also doable since i'm sure eclipse supports this) would solve both issues nicely.

**Comment by keforbes** [comment]
I just implemented #637 so I thought I'd take a stab at this.  Unfortunately, this one is much more complicated.  The search and replace feature already had the concept of a start/end to support line ranges; search only has the concept of a start.  Also, search and replace is more or less implemented by us so I can tweak it as needed; search is mostly passed down to Eclipse and the Eclipse function we call only takes a start index.

At best, I think all I'd be able to do is run the search as normal and if the destination falls outside the current selection, claim it wasn't found.  I'm not quite sure where to shortcut the process to do this though.  I'll spend a little more time thinking about this but I'm not sure if I'll be able to find an acceptable solution.

**Comment by keforbes** [comment]
Ok, I found a way to implement this.  It isn't quite Vim-compliant but I think it's more sensible.  In Vim, if you're in visual mode and you do a `\%V` search, the cursor will move to the first match and update the selection accordingly.  If you're doing a forward search, this means the selection shrunk to the first match so it will never match anything else if you hit `n`.  In Vrapper, the selection will update to follow the cursor position but if you hit `n` or `N` it will still look through that initial selection from when you started your `\%V` search.  As soon as you exit visual mode (or manually move the cursor without `n`/`N`) the "last known selection" will update and any subsequent `n` or `N` will be in this new selection.

If you exit visual mode before doing your `\%V` search then the behavior is identical to Vim.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.67.20160429) which includes this feature.  Go ahead and give it a try if you're still interested in it.
