### ISSUE TITLE
Visual mode and page up/down ctrl U/D

### ISSUE THREAD

**Issue by quicknir** [vrapper/vrapper#731]
When I want to highlight a big block of text, I often switch to visual mode and start hitting ctrl D or pagedown. Often when I do this, it hits a point where it just stops scrolling down or highlighting more text. This doesn't happen when going upwards.

**Comment by albertdev** [comment]
Sadly I cannot recall that I've ever seen this.

In what Eclipse version can you reproduce it, what's your OS / Java version and does the filesize matter?

**Comment by quicknir** [comment]
It's not sadly, it's happily! I see this bug in Java 8, with the latest Eclipse (mars.1), on FC 22, and the file size doesn't really matter (though obviously it needs to be at least a couple of pages in order to be in a position to produce this effect).

I will double check and see if I can repro this on another machine.

**Comment by keforbes** [comment]
@quicknir, were you ever able to reproduce this issue or can I close it?

**Comment by keforbes** [comment]
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.
