### ISSUE TITLE
Searching from last line of file breaks vrapper

### ISSUE THREAD

**Issue by bschlenk** [vrapper/vrapper#733]
When searching from the very last line of a file, I get the exception "Wrong number of hints passed to search mode!" and vrapper completely stops working. The only way to fix it is to disable and reenable the plugin.

The easiest way to reproduce is to type G to go to the bottom and then / and search anything.

**Comment by albertdev** [comment]
Is this for the latest stable version? It sounds a lot like #707 but that should have been fixed by now.

Could you also check your error log what is in there?

**Comment by bschlenk** [comment]
Sorry, forgot to check for updates before posting this. Looks like after updating to the latest version I don't see it anymore. I thought I searched through the issues for that error message...

**Comment by albertdev** [comment]
No problem.

Thanks for immediately reporting back.
