### ISSUE TITLE
Multiple run of a macro with <num> @<reg> broken after update

### ISSUE THREAD

**Issue by borisbrodski** [vrapper/vrapper#737]
Record a very simple macro with: `qqxq`
Then try to run this macro 10 times: `10@q`
And you will get the error:

`Macro @q is called recursively, macro execution aborted.`

**Comment by keforbes** [comment]
Looks like this was introduced by @albertdev's fix for #509.

**Comment by albertdev** [comment]
Ok, that one was easily reproduced...

Seems I forgot to check for this thing, and our test suite doesn't include a test for repeated macros.

So sorry for breaking your workflow, I'll see that it gets fixed soon.

**Comment by albertdev** [comment]
The fix will be included in the next release and unstable build.

Thanks for reporting this regression.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.67.20160406) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!

**Comment by borisbrodski** [comment]
Thank you very much for such a quick fix! :)

The problem is solved. I used the unstable version for a day and it looks good.

PS
I noticed some issues with "function" block ('v i f' and 'v a f'), that I will report later.
