### ISSUE TITLE
Snippet plugin Support?

### ISSUE THREAD

**Issue by tony534** [vrapper/vrapper#740]
Just wondering if Vrapper can support Vim Snippet plugin, like UltiSnips?

**Comment by albertdev** [comment]
Vrapper has no intention of emulating the full extent of VimLanguage. This means that Vim snippet plugins will not be supported unless ported to Java.

Have you check what Eclipse has to offer though? Nowadays Eclipse comes with [Code Recommenders](http://www.eclipse.org/recommenders/) containing hundreds of different snippets for Java.

What kind of files or snippets do you intend to work with in this case?

**Comment by tony534** [comment]
I am working with Apex (Salesforce programming language), which uses eclipse as IDE but no much feature of Java IDE . 

I predefined some snippet to speed up the development in Vim but would like to bring them to Vrapper.

 I will check the SnipMatch link you provide. Thank you for your information.

**Comment by keforbes** [comment]
I agree with @albertdev, I don't think this solution belongs in Vrapper.  Eclipse has lots of different solutions for snippets.

I even found some reference to doing it with your salesforce IDE (force.com?)
http://force-code.com/snippets-in-eclipse/
http://www.tgerm.com/2011/10/visualforce-templates-snippets-forcecom.html
http://apexcoder.blogspot.com/2012/08/extend-eclipse-with-custom-templates.html
