### ISSUE TITLE
vrapper install not available

### ISSUE THREAD

**Issue by espguitarist33** [vrapper/vrapper#742]
I have attempted to install both the stable and unstable releases through both the Eclipse Market place and from the update site directly.

When installing through the Marketplace I get the following: "The following solutions are not available: Vrapper (Vim) 0.66.0. Proceed with the installation anyways?" If I proceed it calculates alternate solutions for some time and then says it cannot be installed.

The stable link no longer shows a version, while the unstable performs the install and then shows the following:
An error occurred while collecting items to be installed
session context was:(profile=C__DeploymentUnit_eclipse_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,net.sourceforge.vrapper.core,0.67.20160429
No repository found containing: osgi.bundle,net.sourceforge.vrapper.eclipse,0.67.20160429
No repository found containing: org.eclipse.update.feature,net.sourceforge.vrapper,0.67.20160429
No repository found containing: osgi.bundle,net.sourceforge.vrapper.plugin.splitEditor.eclipse,0.67.20160429
No repository found containing: org.eclipse.update.feature,net.sourceforge.vrapper.plugin.splitEditor,0.67.20160429

**Comment by keforbes** [comment]
This is some weird Eclipse issue people run into occasionally.  Here are a couple workarounds you can try:
http://stackoverflow.com/a/15897080

**Comment by keforbes** [comment]
The first thing I would try is unchecking the "Contact all update sites" checkbox.

**Comment by espguitarist33** [comment]
Thanks! I was able to see and download the unstable version after doing this.  I was still unable to load anything for the stable site (nor would the drag-and-drop icon from the website work).
