### ISSUE TITLE
Request: Open editor tab by name 

### ISSUE THREAD

**Issue by aberezin** [vrapper/vrapper#744]
I love this plugin and very happy with the strategy of favoring integration with eclipse over trying to impl every vim feature.  
But one I would like is faster nav between tabs. Choosing a buffer by number is not very useful.  I am asking to choose a buffer by name or unique leading characters of buffer name.

`:b MyFile`

**Comment by albertdev** [comment]
Personally I tend to use `Ctrl` + `F6` a lot (Eclipse's Next Editor command) because there I don't need to enter anything, but maybe Eclipse's Quick Switch Editor command is more your style?

Mind that it can be invoked from Vrapper by running `:files` (or currently `:fi` for short).

**Comment by aberezin** [comment]
Thanks @albertdev . I somehow missed the `:fi` and that works great.  This is a bit off topic but is there a command to nav to next error/problem in the open tab?

**Comment by keforbes** [comment]
http://stackoverflow.com/a/1832328

**Comment by keforbes** [comment]
I'm tempted to close this issue since `:files` works for you, but it looks like Vim does actually support `:buffer {bufname}` so this is a legitimate feature request.

**Comment by aberezin** [comment]
You can close imo.  Thanks. 

Regards
Alan

**Comment by keforbes** [comment]
Done.
