### ISSUE TITLE
<C-a> seems broken

### ISSUE THREAD

**Issue by kaptoxic** [vrapper/vrapper#749]
It seems ```<C-a>``` is hijacked from Eclipse (rather than enabling a Vrapper mapping by unbinding key mapping in Eclipse, it seems this key mapping cannot be affected in the key settings). Moreover, selecting _Select all_ from the menu still invokes Vrapper's behaviour. Note that when in Insert mode, select all (and ```<C-a>```) works as expected.

Not sure if this is normal behaviour, but it would be good to have (or be able to revert to the) "old ```<C-a>```" back.

**Comment by keforbes** [comment]
Can you explain a little more about what you're seeing?  Are you saying you've already unbound `Ctrl+A` from Eclipse but you still aren't getting the vrapper increment/decrement behavior?  I'm not sure what behavior you're seeing and what behavior you're expecting.

**Comment by kaptoxic** [comment]
```Ctrl+A``` is bound in Eclipse (*"In dialog and windows"*, as well as *"Editing sources"*) , but it still seems I am getting the Vrapper (increment/decrement?) behavior.

When I press ```Ctrl+A```, Vrapper jumps to the last line without selecting the text (same for when I invoke *Select all* from the Eclipse menu).
However, in Visual and Insert mode, select all, as well as ```Ctrl+A```, works as expected.

**Comment by keforbes** [comment]
Ah, ok, I see what you're saying.  With `Ctrl+A` bound to "Select All" in Eclipse, if I'm in Normal Mode and I hit `Ctrl+A`, the cursor moves to the end of the file and changes to the "operator pending" bar.  If I'm in visual mode or insert mode, it correctly performs the "select all" behavior.  @albertdev, this is another symptom of your visual mode changes just like in #705.

@kaptoxic, we'll have to look into a better solution for this but I can give you a workaround for now.  Unbind `Ctrl+A` in Eclipse and then add the following to your `.vrapperrc` file:
```
nmap <c-a> ggVG
```
This will do a "select all" in vrapper's world so it will be aware of the operation and correctly change to visual mode.

**Comment by kaptoxic** [comment]
Great, the workaround seems to be working as expected. This should help until the more general issue is resolved. Thanks.

**Comment by albertdev** [comment]
It seems commit 860f9f03361f0183369d65525554517ed80092b2 is the culprit. I made that change to make sure the "operation pending" caret would show up but it seems this will clear the selection when you hit a line ending.

**Comment by albertdev** [comment]
Thanks for reporting this issue. A fix will be included in the next release and unstable build.

Note that I also changed one last rendering bug where the caret was shown after the selection. Now it shows inside of it:
![conflicted_selection_caret](https://cloud.githubusercontent.com/assets/1451362/16107428/952489c8-339c-11e6-9b95-187d1923d1c2.PNG)

This corresponds with how Vrapper reacts when you would press `dl` - it will delete the last selected parenthesis `)` and not the next dot as you might have though before.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.69.20160616) which includes this fix.  If you install that version, you should be able to remove the workaround (remove `<c-a>` mapping from vrapper and re-bind `Ctrl+A` in Eclipse) and the select all feature should work.  Please let us know if you have any other issues.  Thanks!
