### ISSUE TITLE
Jump to word under cursor (*, #) behavior changed

### ISSUE THREAD

**Issue by lineinthesand** [vrapper/vrapper#751]
I just recently updated from 0.50 to 0.68 and noticed one change in behavior of the "Jump to next/previous word under cursor" commands (* for next, # for previous): when I am in the word ABC and hit *, it also matches the next ABCD and jumps to this rather than only matching the literal word ABC. When I hit # then, it only jumps to a previous instance of ABCD, so # is no more strictly the opposite of * as it has always been. 
So my question is: is this changed behavior intentional? If so, (how) can I change this back to the previous behavior?

**Comment by albertdev** [comment]
As chronicled in #747 and #750 we are aware of this regression.

Can you update to the latest unstable version and test again?

**Comment by keforbes** [comment]
@albertdev, do you think I should release a 0.68.1 with this fix so people don't have to learn about the unstable build to get this fix?

**Comment by albertdev** [comment]
@keforbes 
If you have the time you can release a hotfix if you feel like it. I don't have any fixes lined up and it looks like we didn't commit anything unstable recently.

**Comment by lineinthesand** [comment]
Thank you so much! Indeed it works as expected with the version from the unstable repo.
