### ISSUE TITLE
Ctrl-F doesn't work on eclipse 4.5.2 and vrapper 0.68.1 on El capitan

### ISSUE THREAD

**Issue by bulletkid** [vrapper/vrapper#753]
Ctrl-f key key isn't mapped to anything on Eclipse on Mac El Capitan 10.11.5 but yet I'm not able to use it. Ctrl-b works well. I wasn't able to map Ctrl-f to Page down in Preferences>keys too. So it does sound like a platform issue.

Currently mapping Ctrl-Shift-f to Page down to make progress

**Comment by keforbes** [comment]
I'm just curious, does Cmd-F behave differently from Ctrl-F?  We had a fix recently to reconcile the behavior between Cmd and Ctrl on a mac.
https://github.com/vrapper/vrapper/issues/679#issuecomment-208312725

**Comment by bulletkid** [comment]
Just tried the unstable build mentioned above on El Capitan eclipse 4.5.2 installation. Sadly it doesn't work. Ctrl-f doesn't do anything while Cmd-f brings up Find/Replace dialog. I'll try using remapping as mentioned in the other issue. Will let you know how that goes.

**Comment by albertdev** [comment]
Can you actually bind `Ctrl-F` to anything in Eclipse and see a result when you press it? It's possible that you have some global shortcut setup which steals it from every app you have.

**Comment by bulletkid** [comment]
Yes. That might be it. I cannot use Ctrl-F at all even when I try setting
it from Eclipse pref page. Lemme look more into global shortcut preventing
this and get back..

Thanks for your help!

Best
Manu

**Comment by keforbes** [comment]
I'm going to close this and assume @bulletkid figured it out and all is well in the world. :smile:
