### ISSUE TITLE
Ctrl-v does paste instead of blockwise selection

### ISSUE THREAD

**Issue by dimovnike** [vrapper/vrapper#755]
is this an intended behaviour? How to switch to blockwise selection?
i'm using stable version.

**Comment by dimovnike** [comment]
installed unstable version but the result is the same.

**Comment by dimovnike** [comment]
solution: had to use ctrl-V (instead of ctrl-v)

**Comment by keforbes** [comment]
In general, if Eclipse has a shortcut defined for a given key press it will always execute that shortcut first without telling Vrapper.  Vrapper only receives key presses if Eclipse doesn't have anything bound to it.  Typically, we tell people to unbind any keystrokes from Eclipse if you want Vrapper to receive them instead.  Of course, the alternative is to just map the key to something else like you did.

In case you hadn't seen it, here's our documentation listing all the Ctrl keys Vrapper supports if you unbind them from Eclipse.
http://vrapper.sourceforge.net/documentation/?topic=commands
