### ISSUE TITLE
nnoremap<leader>t : doesn't work when defined in .vrapperrc

### ISSUE THREAD

**Issue by masterrx** [vrapper/vrapper#756]
It is possible to do the following remappings in command mode:

`nnoremap <leader>t :
`
`nnoremap <leader>e :wincmd k<CR>
`

But when i define the two mappings in the .vrapperc they don't work. 
For `<leader>e` the default normal mode action is executed and for `<leader>t` the following text appears at the bottom status bar 'Global mark not set'.
There are other similar mappings for the leader key in .vrapperc which work. E.g.

`nnoremap <leader>s :
`
`nnoremap <leader>n :wincmd j<CR>
`

The error occurs with eclipse 4.6.0 and vrapper 0.68.1

**Comment by albertdev** [comment]
Do you redefine `<leader>` somewhere using e.g. `let mapleader="\"`? Anything behind it will map to the new leader key whereas everything before it will map to the old or default value.

**Comment by masterrx** [comment]
No i don't. I redefined it in the past, but now i don't use it anymore. Maybe it's some kind of legacy?

As a test I redifined <leader> again, but the behaviour is the same.

**Comment by albertdev** [comment]
Are you sure last two commands in your original report are working fine?

If I read #758 correctly, Vrapper might be executing everything which follows the `<leader>` key, but `n` might not do anything but show an error message if you have no previous search active. It could be that you jump to a different location if you *have* a previous search and run `<leader>n`.

**Comment by masterrx** [comment]
Yes, the two commands are working fine. Beyond that i have several other similar remappings with the leader key, all are working fine. 

It makes slightly sense that for <leader>e the normal e command (jump to the end of the word) is executed. But <leader>t neither my remapping nor the normal t command is executed. But some other command which results in the 'Gobal mark not set' status message.

Just for completeness here my .vrapperrc.
https://github.com/masterrx/vrapperc/blob/master/.vrapperrc

**Comment by masterrx** [comment]
Just recognized that there was a typo in my .vrapperrc file. Now <leader>t remapping works. But the <leader>e remapping is still broken.

**Comment by albertdev** [comment]
Heh, I didn't spot it either. It's such an insidious little transpose that it's not obvious at all.

As for the e mapping, I noticed you have added the `:subwordmappings` command at the end of your `vrapperrc`. As specified in [the documentation for the subwords plugin](http://vrapper.sourceforge.net/documentation/?topic=optional_plugins#subword), this command will run `noremap <Leader>e <Plug>(subword-end)` which overwrites your previous `nnoremap <leader>e :wincmd k<CR>` mapping.

If you still want your custom `<Leader>e` mapping you can try to move it to after the `:subwordmappings` command.

**Comment by albertdev** [comment]
I'm going to label this issue as "Other feedback" as it seems to be primarily caused by the `vrapperrc`.

**Comment by masterrx** [comment]
Great, your last hint was it :subwordmappings overwrote the <leader>e remapping.
