### ISSUE TITLE
:fm / :format does not work in eclipse neo

### ISSUE THREAD

**Issue by mwelt** [vrapper/vrapper#761]
yields to "Not an editor command: fm", same is true for :format

**Comment by albertdev** [comment]
@mwelt Did you by any chance install from the Eclipse Marketplace when you installed Eclipse Neon?

That version should really be renamed to "Vrapper Lite" as it doesn't feature the cool plugins we have. If you have that version then it's best to uninstall it before installing Vrapper [from our update site](http://vrapper.sourceforge.net/documentation/?topic=basics).

**Comment by mwelt** [comment]
@albertdev by any chance indeed i did install from marketplace :), i used your update site and it works like a charm. Thank you so very much!

**Comment by keforbes** [comment]
I might be able to add the optional plugins as "optional" in Eclipse Marketplace now.  I tried doing that a couple years ago but older versions of Eclipse Marketplace would mark *every* plugin for install, which would always fail on some dependency or another.

**Comment by albertdev** [comment]
I'm going to close this issue - after all, everything appears to work now.
