### ISSUE TITLE
how to delete marks?

### ISSUE THREAD

**Issue by glory2013** [vrapper/vrapper#772]
I tried delmarks, but it seems not an editor command.
Does vrapper support delete marks by now? My version is 0.66
Thanks!

**Comment by albertdev** [comment]
You can only do this by waiting for someone to implement the `:delmark` command as it is currently not supported.

I have marked this issue as feature request. [While the Vim command is quite complex](http://vimdoc.sourceforge.net/htmldoc/motion.html#:delmarks), implementing some basic support shouldn't be too hard. It's just that we're short on active maintainers for the moment.

**Comment by keforbes** [comment]
You were lucky to request a small feature while things are still slow for the holidays.  I was able to quickly add this feature but I'm afraid it'll be another couple days before I can update the unstable update site so you can test it.

**Comment by keforbes** [comment]
@glory2013, I've updated the unstable update site with a new build (0.71.20170105) which includes the `:delmarks` command.  Add the unstable update site to your Eclipse and check for updates and it should upgrade everything.  Let me know if you have any problems with it.  Thanks!

**Comment by glory2013** [comment]
@keforbes Awesome! Frankly speaking, I didn't expect to get it solved so quickly. I have experienced the build(0.71.20170105) for some time. It goes so well. Thanks a lot!
