### ISSUE TITLE
install from github instead of sourceforge (my workplace bans sourceforge)

### ISSUE THREAD

**Issue by derekxgl** [vrapper/vrapper#773]
Wondering if I can install from github instead of sourceforge (my workplace bans sourceforge).

**Comment by keforbes** [comment]
There was an attempt to move the update site to vrapper.github.io but we could never figure out how to host binary files without committing them to git.  I don't have time right now to do this the *right* way but just to get you unblocked I uploaded the zip file for our latest release (0.70.0) here:
https://github.com/vrapper/vrapper.github.io/raw/master/vrapper_0.70.0_20160807.zip

Download that zip file, then from Eclipse go to Help -> Install New Software... -> Add... -> click Archive... -> select the vrapper zip.  Hopefully that will work for you.

**Comment by keforbes** [comment]
In the future, I'll need to attach this zip file to the release in GitHub.  I've always just created tags in git, which GitHub interprets as a release, but if I create a release via GitHub's web interface I can attach binary files to it.
