### ISSUE TITLE
Can't map cyrillic symbols in _vrapperrc file(windows)

### ISSUE THREAD

**Issue by Sorcon** [vrapper/vrapper#775]
I want to map all cyrillic symbols to english for normal and visual mode. Example:
nmap й q
nmap ц w
nmap у e
nmap к r
nmap е t
nmap н y
It's work's in eclipse in command mode to map via :nmap й q, but don't work in _vrapperrc file.

**Comment by Sorcon** [comment]
Solved: my text editor created vrapperrc file not in UTF-8 :( Works well in utf-8.

**Comment by keforbes** [comment]
Oh good!  I'm glad you were able to figure that out.  I thought we'd fixed that defect years ago (#94).
