### ISSUE TITLE
Vrapper slows down vertical cursor movement (Ubuntu 16.04)

### ISSUE THREAD

**Issue by tomtom** [vrapper/vrapper#784]
Since lately, vrapper slows down vertical cursor movement to a degree it becomes unbearable. Switching off vrapper (e.g. with the button) solves the problem and vertical movements are fast again. I didn't notice these lags with earlier versions but since I use eclipse mostly under windows (not linux) I cannot guarantee this is true.

Is there a simple way to speed things up?

Regards

**Comment by keforbes** [comment]
Do you have a `_vrapperrc` with some custom settings?  Are you moving vertically inside a large file?  What filetype are you editing when this happens?

I haven't heard of this happening and since I haven't touched vrapper in a couple months it certainly wouldn't be the result of any recent changes.

**Comment by tomtom** [comment]
> Do you have a |_vrapperrc| with some custom settings?

I only set the gvim option.

> Are you moving vertically inside a large file?

No. The filetype doesn't matter.

I noticed that the lags happen in normal mode only. In insert mode 
cursor movements are as fast as if vrapper were disabled. I also noticed 
that the "Highlight the current line" option in Eclipse makes things worse.

> I haven't heard of this happening and since I haven't touched vrapper in 
> a couple months it certainly wouldn't be the result of any recent changes.

As I said I don't use eclipse under linux very often. It could be an 
interaction of several updates that were causing this.

Anyway, I changed some options and everything is running at acceptable 
speed again. It would be nice though if the user manual would describe 
how I can change vrapper's settings so that vrapper's impact on cursor 
movements in normal mode is neglibible.

**Comment by keforbes** [comment]
> It would be nice though if the user manual would describe how I can change vrapper's settings so that vrapper's impact on cursor movements in normal mode is neglibible.

Vrapper's impact on cursor movements are supposed to be negligible without modifying any settings.  None of the settings should affect cursor performance.

Is it possible you're hitting this issue?
https://askubuntu.com/questions/760302/eclipse-neon-mars-is-very-slow-hangs-on-a-fresh-16-04-install-and-upgrade
I guess I can't explain why you were getting better performance after disabling vrapper though...

**Comment by tomtom** [comment]
> Is it possible you're hitting this issue?

I did but this is something different. Anyway, it's running at 
acceptable speed now. Thanks.
