### ISSUE TITLE
How to find eclipseaction command names?

### ISSUE THREAD

**Issue by bennyty** [vrapper/vrapper#788]
Thanks for making Vrapper, it's so shockingly stable and complete compared to many Vi-emulation layers.

When I am customizing in my .vrapperrc I am using eclipseactions (currently stolen from https://github.com/justinmk/config/blob/master/.vrapperrc).

How does one find the `org.eclipse` command that corresponds to the action you wish to take?

**Comment by bennyty** [comment]
I didn't originally create this issue for documentation purposes but I'll self-answer it.

Interestingly enough, in the vrapperrc I linked there is a link (I never actually read them before) that links to some strategies for finding the "the correct JDT voodoo to configure eclipseaction" -justinmk

http://evans-stuff.blogspot.com/2007/10/it-seems-that-im-not-only-one-still.html
https://github.com/vrapper/vrapper/issues/265

**Comment by bennyty** [comment]
Actually I'm going to reopen this issue. It seems like the two listed ways don't work very well. It didn't help me find how to emulate Eclipse's Open Declaration (F3 by default) with vim's gd and gD)

**Comment by keforbes** [comment]
Glad you're enjoying Vrapper!

I mentioned [here](https://github.com/vrapper/vrapper/issues/413#issuecomment-40313452) that I think you need the 'PDE - Plug-in Development Environment' installed.  Although, I made that comment in 2014 so who knows if it's still accurate.

**Comment by keforbes** [comment]
I'm going to close this since it isn't actually a Vrapper issue.  It's a lack of easily accessible Eclipse documentation.

**Comment by tecfu** [comment]
> Thanks for making Vrapper, it's so shockingly stable and complete compared to many Vi-emulation layers.
> 
> When I am customizing in my .vrapperrc I am using eclipseactions (currently stolen from https://github.com/justinmk/config/blob/master/.vrapperrc).
> 
> How does one find the `org.eclipse` command that corresponds to the action you wish to take?

See the commands here: https://github.com/pellaton/eclipse-cheatsheet/blob/master/eclipse4.9/shortcut-export-eclipse-win-4.9-sorted.csv
