### ISSUE TITLE
Visual mode:  Home and End keys revert to normal mode and text selection is lost

### ISSUE THREAD

**Issue by lukedegruchy** [vrapper/vrapper#789]
In gVim when in visual mode, the Home and End keyboard keys will select from the cursor position to the beginning/end of line, respectively.

In vrapper, when in visual mode, the Home and End keys will move my cursor to the beginning and end of the line, but vrapper will revert to normal mode and the text selection will be lost.   Conversely, 0 and $ will maintain visual mode and the text selection.

Apologies if this is a duplicate, but I searched for an existing bug similar to this one and didn't find one.

**Comment by keforbes** [comment]
Yep, it's a duplicate. :smile: You can see my comment here: https://github.com/vrapper/vrapper/issues/757#issuecomment-238655471 as well as issues #503 and #370.

The short answer is: unbind those keys from Eclipse then Vrapper will receive them.

**Comment by lukedegruchy** [comment]
Works like a charm!   Thank you!
