### ISSUE TITLE
Site at sourcefource is down

### ISSUE THREAD

**Issue by robertpro** [vrapper/vrapper#795]
Hello, I am trying to install the plugin but I can't since the [page](http://vrapper.sourceforge.net/) is down, can you provide an alternative way to install the plugin?

**Comment by albertdev** [comment]
Thanks for your interest in Vrapper and letting us know.

It looks like sourceforge might be in trouble but github still hosts [the off-line update site of version 0.72.0](https://github.com/vrapper/vrapper/releases/download/0.72.0/vrapper_0.72.0_20170311.zip) (click for download). Add it as an [archived software site](https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-127.htm) and continue as usual.

Just make sure you delete that update site later on when the regular Eclipse update site URLs are back online.

**Comment by robertpro** [comment]
Working!, thanks!
