### ISSUE TITLE
writing a dot ('.') in a macro is not recorded

### ISSUE THREAD

**Issue by The-Phi** [vrapper/vrapper#796]
How to reproduce this:

<kbd>q</kbd><kbd>a</kbd>

then:

<kbd>esc</kbd><kbd>i</kbd> `this.is.a.test`

<kbd>q</kbd>

If we trigger the macro:

<kbd>@</kbd><kbd>a</kbd>
=> Result: `thisisa.test` 

The last `.` is recorded, but not the first ones?

**Comment by keforbes** [comment]
I tried reproducing this in both Eclipse Neon and Eclipse Oxygen and in both cases it worked fine; running the macro resulted in `this.is.a.test`.

What version of Eclipse are you using?  What version of vrapper?  What OS?  What type of file were you editing at the time?  Do you have any custom bindings defined in `.vrapperrc`?

**Comment by albertdev** [comment]
If I try to reproduce this inside a function of a Java file, sooner or later the code completion dialog pops up and I have to dismiss it to type the next dot.

Do you see something similar, and if so, what did you do to dismiss it? It's possible that Eclipse steals those extra characters.

**Comment by The-Phi** [comment]
Sorry for the delay, I've missed the notification somehow.

my config:
```
Eclipse for JavaScript and Web Developers

Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

PyDev 6.0.0.2010919
 Vrapper	0.72.0	net.sourceforge.vrapper.feature.group	Vrapper Team
```
I'm on `4.9.58-1-MANJARO x86_64 GNU/Linux`

I've tried on `.py`   => NOT WORKING
**But, I've found it it's normal with `.html`, `.js`, `.css` and `.txt` files!**

So I guess it's a problem with PyDev which makes it incompatible with vrapper but I don't know why?
