### ISSUE TITLE
Bug pasting unnamed register in visual mode

### ISSUE THREAD

**Issue by BradleySmall** [vrapper/vrapper#797]
select some text into the unnamed buffer with (yw) 
visual column highlight a few lines (ctrl-v jjjj)
then choose to prepend all lines "I"
paste unnamed buffer (ctrl-r ")
exit paste mode (ESC)
expected: the yanked word should now prepend each line of the vertical selection.
actual: the yanked word prepends only the first line of the selected block
If, you use (ctrl-v) perhaps this is an x-ray through to eclipse bindings instead of (ctrl-r ") it works as expected, but you have to do the yank with the system register ("+yw)

**Comment by keforbes** [comment]
If I use `p` to paste the unnamed buffer rather than `ctrl-r "` it works for me.  That is, `yw` `0` `ctrl-v` `jjjj` `p`.

I can reproduce the issue when using your steps with `I` though.  I'm guessing this is an issue with moving from `visual block` mode to `insert` mode to `paste register` mode.  Exiting paste mode is returning to insert mode but it probably lost the context that insert mode needs to go back to visual block mode.

**Comment by BradleySmall** [comment]
Thanks for responding keforbes. Although I can use the (p) to do a paste from insert mode, it will not work in visual mode.

**Comment by BradleySmall** [comment]
Here is what it should look like:
WORD     <--- copy this with (ye)

XXX               <- C-v
XXX               <- j
XXX               <- j

WORDXXX        <- C-r " ESC
WORDXXX   
WORDXXX 

Result should look like that.

**Comment by keforbes** [comment]
Right, I understand the scenario.  I still believe there is a valid workaround of `ctrl-v` `jjj` `p`.  That's pasting from visual block mode, not entering insert mode to do the paste.  Although you'd have to hit `0` first to move the cursor to the first column to be synonymous with `I` in visual block mode.

That was just to provide you with a workaround; if I perform the actions as you described (`I` `ctrl-r` `"`) then I *can* reproduce this issue.  Sorry if that wasn't clear in my previous comment.  Or am I misunderstanding your recent comment?

**Comment by BradleySmall** [comment]
Actually, as a work around, I can do the copy and paste using C-c or C-Insert and use the C-v or S-Ins while in Visual insert mode, and it will work. But that isn't want the fingers want to do :) Worst case I can still use the column mode in Eclipse AS-a which I am pretty used to doing as well.

**Comment by albertdev** [comment]
@keforbes guess was correct, the register insertion would lose Insert mode's special state which triggers the final block editing code. Apparently we never carried it across during pasting from a register.

Fixed in commit 00db4568b0bf18cc2227addbea2c313a7d36ff61.

**Comment by keforbes** [comment]
@albertdev, I updated the unstable update site with this fix but after installing this latest build Eclipse is constantly crashing with a `java.lang.StackOverflowError`.  This is in Eclipse Oxygen.  Can you test out this build and see if it happens to you?  I had to disable Vrapper to get the error to stop occurring.

**Comment by albertdev** [comment]
@keforbes Can you share the stacktrace? I've just installed it as a dropin in my Oxygen install (which isn't updated yet, mind you) but could not trigger such a crash yet.

**Comment by keforbes** [comment]
@albertdev, sorry, Eclipse just popped up a window that said `java.lang.StackOverflowError` and the details button just showed the same error (no stack trace).  Hopefully I'll have time tonight to look at the actual error log and see if I can find any more info.

**Comment by keforbes** [comment]
@albertdev:
```
org.eclipse.ui
Error
Tue Oct 10 22:12:39 MDT 2017
Unhandled event loop exception

java.lang.StackOverflowError
	at org.eclipse.swt.widgets.Caret.getSize(Caret.java:275)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:71)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:76)
	at org.eclipse.swt.widgets.Caret.setLocation(Caret.java:493)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:71)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:76)
	at org.eclipse.swt.widgets.Caret.setLocation(Caret.java:493)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:71)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:76)
	at org.eclipse.swt.widgets.Caret.setLocation(Caret.java:493)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:71)
	at net.sourceforge.vrapper.eclipse.ui.CaretUtils$EvilCaret.setLocation(CaretUtils.java:76)
	at org.eclipse.swt.widgets.Caret.setLocation(Caret.java:493)
```

**Comment by albertdev** [comment]
I see, that's caused by changes in commit c9de14cceafd362ca3c191230622dc69c9f3ba5f after I noticed that Eclipse Neon's point-1 release would no longer display the caret right.

It seems these changes work fine on Windows but backfire on Linux, which means the SWT platform runs wildly different code on different platforms. :(

**Comment by albertdev** [comment]
@keforbes OK if we move this conversation to Gitter?

**Comment by keforbes** [comment]
@BradleySmall, sorry for the back-and-forth with build issues.  I finally updated the unstable update site with a new build (0.73.20171016) which includes this fix.  Please update to that version and let us know if you have any other issues.  Thanks!
