### ISSUE TITLE
visual mode doesn't select when pressing ctrl+home or ctrl+end

### ISSUE THREAD

**Issue by dennis97519** [vrapper/vrapper#801]
On vim this visual selects to start and end of the document.

Nevermind, I think this issue is macOS specific. Same thing doesn't work in vim on mac too, even after adding a keybinding file.

**Comment by keforbes** [comment]
I'm not sure if you've already done this, but make sure you unbind `home` and `end` in the Eclipse settings.  Vrapper only receives a keypress if it isn't already bound to an Eclipse operation and by default `home` and `end` are actually bound to Eclipse operations.

After you unbind `home` and `end` vrapper will be able to keep its state so you can press `v<end>` and it will go into visual mode then select to the end of the line.  Although, vrapper doesn't have `ctrl+home` or `ctrl+end` bound to anything so your use case still doesn't work.

I'll flag this as a feature request.  We should be able to add a mapping for `start of document` and `end of document` to those keys.  In the meantime, you could just add the following to your `.vrapperrc`:
```
map <c-home> gg
map <c-end> G$
```

**Comment by dennis97519** [comment]
Thanks for the mappings, I'm guessing this problem is macOS specific and the functionality might work on other systems, because in the actual vim editor on mac the same key combinations don't work too, but when sshing over to a Linux system c-home and c-end works.
