### ISSUE TITLE
SpaceVim style line number display

### ISSUE THREAD

**Issue by PengZheng** [vrapper/vrapper#802]
I found the SpaceVim's way of displaying line number is very handy for jumping to a specific line.
![nvim_line_number](https://user-images.githubusercontent.com/5362947/33526163-ccfbc77c-d877-11e7-9fc7-87dd19de8fdf.png)

**Comment by albertdev** [comment]
Ah yes, relative line offsets.

Vrapper tries to change as few things possible to support a wide array of editors without breaking their specifics. However, we've had this request before as #65 and back then we had @matf chime in with their custom Eclipse plugin doing just such a thing. Give it a try:

http://matf.github.com/relativenumberruler

Hope that helps, and thanks for using Vrapper!

**Comment by PengZheng** [comment]
It works perfectly!
Thank you guys for making this great plugin.

**Comment by keforbes** [comment]
Glad you're enjoying Vrapper!  I'm going to close this issue since it's addressed by another plugin.
