### ISSUE TITLE
Icon not appearing after installation on Oxygen 1a

### ISSUE THREAD

**Issue by benhjt** [vrapper/vrapper#804]
Using Oxygen.1a Release (4.7.1a) on Windows 10.

I have installed the plugin via the marketplace as well as the update site. After installing there is no icon in the tool bar and there is also no options in the preferences relating to vrapper. I have checked the error log and can't see anything relating to vrapper.

**Comment by albertdev** [comment]
Sorry to hear that Vrapper is not immediately working for you.

Where did you place your Eclipse install? We have heard reports of people who extracted an Eclipse `.zip` file in their `C:\Program Files` folder and had trouble installing Vrapper until they installed Eclipse in another folder (I can't remember if that had something to do with UAC or the space in the folder name).

Have you tried creating a new workspace? Can you see the Vrapper plugin in your "Installed plugins" list in Eclipse's About screen?

**Comment by benhjt** [comment]
Eclipse is installed in `C:\Program Files`. I gave up in the end and reinstalled eclipse as I had been getting an error about something else for a while. With this new install, vrapper works as expected so I'm happy for this to be closed.
