### ISSUE TITLE
Relative line numbers

### ISSUE THREAD

**Issue by marier-nico** [vrapper/vrapper#805]
I just have a feature request I thought I could put in here, not sure how easy or not it would be to implement, but relative line numbers would be a really nice thing to have.

**Comment by keforbes** [comment]
Please try installing the Relative line ruler plugin from http://matf.github.io/relativenumberruler/
(source at https://github.com/matf/relativenumberruler )

It was actually designed to work together with Vrapper.

**Comment by marier-nico** [comment]
Thanks a bunch for the help, that works perfectly!
