### ISSUE TITLE
{o, O} open new line and insert not working with doxygen member variable comments

### ISSUE THREAD

**Issue by fredheidrich** [vrapper/vrapper#806]
Opening a new line from a member variable like so: 

```c++
int someint; //!< fancy member  doxygen doc comment
int someint; ///< another fancy doxygen doc comment
int someint; /// a third fancy doxygen doc comment
```

doesn't seem to work, 'o' gets an error message and 'O' just jumps to the next line

Inside` /*! */` it works fine

Windows 7
e2 studio IDE is based on Eclipse SDK 4.5.2 (Mars.2)
and CDT version 8.8.1.

**Comment by keforbes** [comment]
Can you provide a little more detail?  What error appears when you type `o`?

Also, can you look at the error log and see if there are any stack traces related to `net.sourceforge.vrapper`?  I'm not sure about Eclipse Mars, but to get to the Error Log it should be something like Help -> About Eclipse -> Installation Details -> Configuration -> View Error Log.
