### ISSUE TITLE
Count not working with camelcasemotion objects

### ISSUE THREAD

**Issue by borisbrodski** [vrapper/vrapper#807]
Using CamelCaseMotion plugin I can do following:

    MyVeryCo|olClassName

with `'|'` denoting the cursor position. Now pressing `ci<Leader>` I can replace the `Cool` with the new text:

    MyVery|ClassName

What's cool! Now if I want to replace two consequent CamelCase-parts I should be able to do `c2i<Leader>` removing `CoolClass`:

    MyVery|Name

This works in vim (with vim version of "camelcasemotion" plugin) but doesn't work in vrapper.
Please, fix this!

I'm using latest stable version (0.72.0).
Thank you.

**Comment by keforbes** [comment]
Well, crap, you're right.  I implemented support for counts in motions (`2\w`) [here](https://github.com/vrapper/vrapper/blob/5d3825612e1f8723c0eb2ccca3319dbb92010964/plugins/ports/net.sourceforge.vrapper.plugin.subwordtextobj/src/net/sourceforge/vrapper/plugin/subwordtextobj/commands/SubwordMotion.java#L59) but not when calculating ranges (`c2i\`) [here](https://github.com/vrapper/vrapper/blob/5d3825612e1f8723c0eb2ccca3319dbb92010964/plugins/ports/net.sourceforge.vrapper.plugin.subwordtextobj/src/net/sourceforge/vrapper/plugin/subwordtextobj/commands/SubwordMotion.java#L164).  `count` is being passed in as a method argument, I'm just ignoring it.

Unfortunately, I don't really have time to spend on this project anymore.  I'd be happy to accept a Pull Request if you're willing to fix this yourself though. 😄  It should be relatively straightforward, the entire code change would be restricted to that `getRegion` method.

**Comment by keforbes** [comment]
Just a quick note in case you're willing to implement this yourself.  The solution might require an outer method with a loop just like the `destination` method loops and the `doIt` method performs the actual work.  When I said the code change would be restricted to `getRegion` I didn't mean you had to limit yourself to that one method.

**Comment by borisbrodski** [comment]
Thank you for the hints! That's great! I'm on it.
