### ISSUE TITLE
Cursor shift one position left in Insert mode

### ISSUE THREAD

**Issue by gaidink** [vrapper/vrapper#809]
Normal mode:
![screen shot 2018-02-22 at 10 37 59 pm](https://user-images.githubusercontent.com/9530194/36552949-215a79c4-1821-11e8-9e4e-d46f82e7c9af.png)

Insert mode (after hitting "i"):

![screen shot 2018-02-22 at 10 36 24 pm](https://user-images.githubusercontent.com/9530194/36552990-3eae8fec-1821-11e8-8f92-a0850541af7d.png)

The intended position be after ">"

It was installed using Eclipse Marketplace.
How do I fix this?

**Comment by albertdev** [comment]
I'm sorry, but I don't understand your question.

 As far as I can see it is normal Vim behaviour to put the caret in front of that `>` character [when you press `i` (see Vim docs)](http://vimdoc.sourceforge.net/htmldoc/insert.html#i). And similarly, pressing `a` should put the caret behind the `>` character.

If you are comparing with Vim, do you happen to run any custom plugins or a downloaded plugin collection?

**Comment by gaidink** [comment]
Yes, you're right. My silliness. Sorry about that. It's been a while I haven't used block cursor.

And another one more, I am not able to point the cursor behind `>` which I can on vim using iTerm.
