### ISSUE TITLE
vrapper.sourceforge.net is down

### ISSUE THREAD

**Issue by unaiur** [vrapper/vrapper#810]
I've been trying to install vrapper for some days but the sourceforge page is down.

**Comment by cwt** [comment]
me too, but I can download it directly from here https://sourceforge.net/projects/vrapper/files/

**Comment by keforbes** [comment]
Yeah, they've been having trouble lately.  I dumped the most recent builds on our dummy github site just as a backup.  You should be able to add it as an update site.
https://vrapper.github.io/update-site/vrapper-stable/
