### ISSUE TITLE
c[Return] and c- do not behave correctly

### ISSUE THREAD

**Issue by daemonblade** [vrapper/vrapper#822]
On vi/vim, with a file containing:
```
a
b
c<Cursor on this line>
d
e
```

Using "c[Return]" results in:
```
a
b
<Cursor on this line - insert mode>
e
```

But in vWrapper, we get:
```
a
b
c
<Cursor on this line - insert mode>
```

Similarly, if we start with:
```
a
b
c<Cursor on this line>
d
e
```

On vi/vim, "c-" results in:
```
a
<Cursor on this line - insert mode>
d
e
```

But on vWrapper, we get:
```
<Cursor on this line - insert mode>
c
d
e
```

**Comment by albertdev** [comment]
Thanks for this report, and sorry for waiting so long to get back to you. I can reproduce this and can confirm that Vrapper is not handling this right.

It will take a little time to investigate though as I want to code up some test code first.

**Comment by albertdev** [comment]
Oh, I nearly forgot: the title mentions "Visual mode" but you're never switching to Vrapper's visual mode using <kbd>v</kvd> or <kbd>V</kbd>. Is there some other case where things also go wrong or is it just a little error in the title?

**Comment by daemonblade** [comment]
I actually mean the "command" mode, ie the mode you're in after hitting [Esc] several times.

**Comment by albertdev** [comment]
This is fixed in the next release and unstable build.

Thanks again for helping to improve Vrapper!

**Comment by keforbes** [comment]
Ok @daemonblade, I've updated the unstable update site with a new build (0.75.20190210) which includes these changes.  Please give them a try and let me know if you hit any more issues.  Thanks!

**Comment by daemonblade** [comment]
Thanks!
