### ISSUE TITLE
Installation issue with Eclipse CDT 2020-06

### ISSUE THREAD

**Issue by XavierT** [vrapper/vrapper#831]
I have just installed the latest release of CDT 2020-06, and I don't manage to install either the stable or unstable version of Vrapper.

The issue might be on my end as well, because I don't really understand eclipse package dependencies, but I have just installed the vanilla CDT and got the following dependency error when trying to install Vrapper 0.75.20200603 from update site :

```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 14.0.0
  Software currently installed: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
  Cannot satisfy dependency:
    From: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tools.templates.freemarker.java11 [1.1.100.202001140305,1.1.100.202001140305]
  Cannot satisfy dependency:
    From: Template Engine Freemarker Support (Java 11) 1.1.100.202001140305 (org.eclipse.tools.templates.freemarker.java11 1.1.100.202001140305)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))
```

Any help or suggestion appreciated

**Comment by XavierT** [comment]
Found a similar issue being discussed here, and referencing a CDT mailing list :

https://stackoverflow.com/questions/62648135/error-installing-devstype-plugin-for-eclipse

This does not seem to be Vrapper specific

**Comment by keforbes** [comment]
Thanks for the update, I'm glad you got it working!  I guess we should probably look into updating Vrapper to use Java 11.  We kept Java on and older version for backwards compatibility but it looks like it might finally be time to update some things.
