### ISSUE TITLE
Unable to use vim-selection when using on Eclipse 2020-06 on macOS Big Sur (Developer's Beta)

### ISSUE THREAD

**Issue by amannougrahiya** [vrapper/vrapper#833]
When Vrapper is enabled on my Eclipse 2020-06, running on macOS Big Sur (Developer's Beta), I am facing the following issue: When I am using Ctrl-v, or Shift-v to select text, the blue-highlighting of the box is not visible. Further, only the last characters of each word (or of the last word of a sentence) are getting marked. Pressing Esc doesn't remove the markings. The screen stops refreshing properly upon scrolling, or jumping to any definition/use/declaration of Java elements.
This problem is reproducible.
I also tried using some older versions of Eclipse (as far back as Oxygen), but to no avail.

As my work heavily depends on using Eclipse, I had to rollback to a stable version of macOS via Time Machine. Clearly there are some compatibility issues here between Vrapper and macOS Big Sur. 

p.s.: If the developers of Vrapper feel that this issue will get resolved with the stable release of macOS Big Sur, we can close this issue. Otherwise, it would be really helpful if this issue can be resolved.

**Comment by keforbes** [comment]
I'm sorry, I don't have a mac so I can't troubleshoot this.  @albertdev?  Are you able to reproduce this issue?

**Comment by amannougrahiya** [comment]
An update: I also tried using Vrapper with Eclipse (2020-06) on a fresh install of the latest version of macOS Big Sur (11.0 Public Beta 1). Unfortunately, the problem still persists.

Thanks for looking into this issue.

**Comment by albertdev** [comment]
@keforbes I do not own an Apple computer so I will not be able to test things.

@amannougrahiya What happens if you open Eclipse and disable Vrapper, then make selections using <kbd>Shift</kbd>+ <kbd>Left</kbd> / <kbd>Right</kbd>?
What if you do "Extend selection" using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Page Up</kbd>?

I'm mainly wondering if it is an Eclipse issue, in which case it needs to be reported there as soon as possible.

**Comment by albertdev** [comment]
By the way, have you checked the Eclipse error log? Eclipse platform errors could be stopping Vrapper from working.

**Comment by amannougrahiya** [comment]
@albertdev I have tried both those kinds of selections in Eclipse after disabling Vrapper -- they work as expected. As soon as I enable Vrapper (using the toggle button at top), the problem recurs. In fact, this is the main reason why I had decided to share the issue here, instead of at Eclipse's repository.

Please note that all the other functionalities of Vrapper work perfectly well, except for these selection-related refreshing/highlighting issues.

I couldn't check Eclipse error log. I will wait for the next release of macOS's Public Beta (which should be released hopefully within a month) before reinstalling the complete setup and trying it out again. As my work heavily relies on Eclipse, I have rolled back to macOS Catalina for now.
I'll update this thread if/when I find any further information in this regard. Thanks.

**Comment by peop81** [comment]
Can confirm this is still an issue on Big Sur release version

**Comment by amannougrahiya** [comment]
I had no option but to switch the IDE itself as a result of this issue. Now I am using IntelliJ IDEA instead of Eclipse.

**Comment by peop81** [comment]
Just an update, it's now working correctly under Eclipse 2020-12!
