### ISSUE TITLE
InputInterceptorManager and BufferInfo prevent garbage collection

### ISSUE THREAD

**Issue by eliericha** [vrapper/vrapper#835]
Hello folks,

After noticing ever increasing memory usage (and ultimately memory exhaustion) in my Eclipse application I investigated and traced the issue to InputInterceptorManager preventing the garbage collection of a massive tree of objects.

Here's my analysis. It would be great if someone could confirm it before I try a fix.

InputInterceptorManager has a `WeakHashMap<IEditorInput,BufferInfo>` called `activeBufferIdMapping`. When analysing a Heap Dump in VisualVM I found that the of my massive tree of objects is an IEditorInput kept alive by a reference from activeBufferIdMapping. Even though it's a `WeakHashMap`, there's a subtlety: only the keys of the map are weak references, the values of the map are strong references. `BufferInfo` has a strong reference to the `IEditorInput` so that's what's keeping my massive object tree alive and preventing garbage collection.

Note that the documentation of `WeakHashMap` warns against values having strong references to their keys:

> The value objects in a WeakHashMap are held by ordinary strong references. Thus care should be taken to ensure that value objects do not strongly refer to their own keys, either directly or indirectly, since that will prevent the keys from being discarded.

Does that make sense to anyone else?

So I suggest to turn the `IEditorInput` strong references in `BufferInfo` into weak references to enable garbage collection.

If we agree on that solution I can submit a pull request.

Thanks,
Elie

**Comment by keforbes** [comment]
If you can create a pull request that resolves the issue then by all means, submit it!  I'll make sure to run the unit tests and some sanity checks.

**Comment by eliericha** [comment]
Here you go! Let me know what you think.

And actually I'm realizing now that I haven't properly checked that it solves my original issue. To do that I'll have to build an update site, install in my other Eclipse and observe with VisualVM.

So I guess stand by until I do that!

**Comment by eliericha** [comment]
Ok I just tried it and I confirm that it solves the problem in my other Eclipse setup 👍

**Comment by keforbes** [comment]
I updated the unstable update site with a new build (0.75.20200909) which includes this change.  So you can just add the unstable update site and 'Check For Updates' to pull in this change for your other Eclipse setups.

**Comment by eliericha** [comment]
That's great, thanks!
