### ISSUE TITLE
ctrc+c 

### ISSUE THREAD

**Issue by rocketmagnet83** [vrapper/vrapper#840]
Hello, 
i'm realy happy with the plugin but sometimes it decides to now recoginze the ctr+c key anymore which i need to switch from text to editmode and that very unpleasant.

i don't know how to reporduce this error but it appears on a regular basis.
i hope that helped and that you are able to fix the bug

**Comment by rocketmagnet83** [comment]
i'm using debian 10 with the windowmanager MATE.

**Comment by keforbes** [comment]
Closing duplicate.
