### ISSUE TITLE
Can't change to a different tab that is far away with <C-w><number>gt

### ISSUE THREAD

**Issue by wnim** [vrapper/vrapper#852]
For example  `<C-w>4gt` would move me 4 tabs to the right in vim.
Can this be implemented in vrapper?

**Comment by keforbes** [comment]
Just to clarify, `4gt` already goes to the 4th tab in vrapper.  But you want to move 4 tabs forward from your current tab?  Looking at the gvim docs, I see this:
```
CTRL-W gt						*CTRL-W_gt*
		Go to next tab page, same as `gt`.

CTRL-W gT						*CTRL-W_gT*
		Go to previous tab page, same as `gT`.
```
and for `gt`
```
{count}gt	Go to tab page {count}.  The first tab page has number one.
```
It sounds like vrapper is already consistent with gvim behavior.  Although, I believe all of our `<C-w>` commands are provided by our [Split Editor Plugin](http://vrapper.sourceforge.net/documentation/?topic=optional_plugins#split) and I'm not sure if that plugin supports a `{count}` for `<C-w>gt`.

Can you clarify if you're looking for behavior different from `4gt` or if you just want to add support for `<C-w>4gt` to do the same thing?

**Comment by wnim** [comment]
You are right.
My bad.

cheers
