### ISSUE TITLE
Add ":wrap" command line command bind to Eclipse's action "Toggle Word Wrap"

### ISSUE THREAD

**Issue by wnim** [vrapper/vrapper#853]
Hi,
Eclipse has a "Toggle Word Wrap" action and button, is it possible to invoke it through a command-line "wrap" command?

Thanks,
Wnim

**Comment by keforbes** [comment]
Vrapper has the ability to map any Eclipse operation to a custom command if you know the operation name.  For Toggle Word Wrap, I believe the operation is:
```
org.eclipse.ui.edit.text.toggleWordWrap
```
Which means, if you wanted to set it to a custom command like `:wrap`, you would add this to your `.vrapperrc` file:
```
 eclipseaction wrap org.eclipse.ui.edit.text.toggleWordWrap
```

Here's a cheat sheet of Eclipse operation names in case you want to define more custom commands:
https://github.com/pellaton/eclipse-cheatsheet/blob/master/eclipse4.17/shortcut-export-eclipse-win-4.17-sorted.csv
