### ISSUE TITLE
Adding DVT (a SystemVerilog plugin) action to vrapper keymaps

### ISSUE THREAD

**Issue by wnim** [vrapper/vrapper#855]
Hi,

In the documentation it is mentioned that some language-specific commands are enabled because vrapper leverages the existing Eclipse plugins such as JDT.

I'm coding in SystemVerilog with the plugin DVT from AMIQ.

I spoke with AMIQ, and they provided me with these Eclipse actions:

ro.amiq.vlogdt.ui.editor.ToggleComment
ro.amiq.vlogdt.ui.editor.FormatSource
ro.amiq.vlogdt.ui.editor.OpenDeclaration
ro.amiq.vlogdt.ui.editor.actions.RefactorRename

Meaning that it should be possible to implement gcc, gd, gR and ":format".

Regarding :format, I already know I can do it myself by (tested and works):

eclipseaction format ro.amiq.vlogdt.ui.editor.FormatSource

But I'm unsure how to map actions to keymappings and not an ex-command, which is required for gcc, gd and gR
Is there a way?

If it's simple maybe it's worth for vrapper to support this natively. 

With better tools for writing SystemVerilog code we could all enjoy better hardware :).

Thanks,
wnim

**Comment by keforbes** [comment]
Just a quick update... you can do something like this:
```
eclipseaction findref org.eclipse.jdt.ui.edit.text.java.search.references.in.workspace
nmap gr :findref<enter>
```
Basically, you can define a custom command like `:findref` and then map that command to a "normal mode" key combo like `gr` using `nmap`.

So for your case, you can do something like:
```
eclipseaction verilogdeclaration ro.amiq.vlogdt.ui.editor.OpenDeclaration
nmap gd :verilogdeclaration<enter>
```
and that should work for you.

**Comment by wnim** [comment]
Thanks!
