### ISSUE TITLE
Vim doesn't work on windows of Table views

### ISSUE THREAD

**Issue by Xemptuous** [vrapper/vrapper#856]
I have my `<TAB>` and `<S-TAB>` keys setup for switching buffers using `:bnext` and `:bprev`, but I noticed that whenever the buffer switches to a view of a Table in my db, vim status line disappears, can't use vim commands, and it shuts down entirely.

Would be nice to be able to continue switching buffers around even when hitting a window like that (working outside of just sql scripts).

**Comment by keforbes** [comment]
Unfortunately, Vrapper works by hooking into Eclipse's Editor API calls.  This means any time you have a view active which doesn't extend the Editor class, Vrapper can't do anything.  This is because it doesn't actually run at the workspace-level, it runs at the editor-level.

**Comment by albertdev** [comment]
@keforbes @Xemptuous We do have the changes for #820 sitting on the "Unstable Software Site" which might allow some things to happen. Sadly we haven't gotten any new feedback on that pull request and it's still in need of some documentation.

Here's what I would do to the Eclipse shortcuts after installing that version:

* Find the "Activate Editor and Type" shortcut. Click on the Binding field and press backspace to clear the default binding, then press <kbd>Escape</kbd>.
![image](https://user-images.githubusercontent.com/1451362/205721510-464befd1-02fb-4969-99a4-162b9f868bfe.png)
* Find the "Toggle Vrapper" shortcut and make sure something is assigned. I used <kbd>Ctrl+Shift+F12</kbd>. This is used to disable Vrapper if you get stuck (though there should be a button you can click in the toolbar as well).
* Find "Next Tab", press Copy Command and then click on the line where there is no binding. Change the "When" dropdown to "Vrapper Enabled on a View", then click on the little arrow next to Binding:
![image](https://user-images.githubusercontent.com/1451362/205721968-945556f9-1255-4bd9-9808-5989d1e21923.png)
* Do the same for "Previous Tab".
* Click Apply and Close.

Now when you jump to a view at the bottom or so you can keep pressing <kbd>Tab</kbd> / <kbd>Shift-Tab</kbd> to toggle views.

If you encounter those database views inside of the main editor "block" then things get more complicated. I tried binding the keys to basically the entire editor, but then I could no longer use <kbd>Tab</kbd> to indent code, so your mileage may vary. I might be able to tell more if you post a screenshot of your Eclipse layout.
