### ISSUE TITLE
Need to integrate vim and emacs plugin

### ISSUE THREAD

**Issue by shakkir-synopsys** [vrapper/vrapper#862]
In Vrapper, can we use the Vim plugin written in the Vim script and the Emacs plugin written in Elisp?

**Comment by keforbes** [comment]
I'm sorry, no.  You can only use commands implemented by Vrapper (listed here: https://vrapper.sourceforge.net/documentation/?topic=configuration) or install our own custom plugins (listed here: https://vrapper.sourceforge.net/documentation/?topic=optional_plugins).  We don't support vimscript or elisp.
