### ISSUE TITLE
Shift-P/Capital P in visual mode should not yank the selected text to the register

### ISSUE THREAD

**Issue by ricfwolff** [vrapper/vrapper#873]
Steps to reproduce:

Write the following text:

`abc 123 456 789 def`

Now select (visual) "abc" and [y]ank.

Then select (visual) 456 and [P]aste. 

Then select (visual) def and [P]aste again.

Expected result:

`abc 123 abc 789 abc` 

Wrong result:

`abc 123 abc 789 456`

This is happening to me on DBeaver, when using vrapper with it. If it's been fixed, but DBeaver does not have the latest version, sorry for that.

According to this feature that was implemented "recently", the "P" (capital P, shift+P) when in visual mode should not yank the selected text to register memory:

https://vimhelp.org/change.txt.html#v_P

Source: https://superuser.com/a/1759793/1261683

**Comment by albertdev** [comment]
Most of the work on Vrapper was done before 8.0 was even out so this never made it in. I never realized this was added to Vim BTW, and it does seem like a nice shortcut to add.

**Comment by ricfwolff** [comment]
Yes, I like this shortcut a lot!

Thank you!
