### ISSUE TITLE
How to change search highlight color?

### ISSUE THREAD

**Issue by awvalenti** [vrapper/vrapper#879]
![image](https://github.com/vrapper/vrapper/assets/834921/0fc29d15-c6fb-4360-aa00-0193f3e0f23a)
This background color appears when I do a Vrapper search (e.g., press `*` on a word). I'd like to change it.

I found that it's defined as `colorPreferenceValue="240,216,168"` at `plugins/net.sourceforge.vrapper.eclipse/plugin.xml:118`:

![image](https://github.com/vrapper/vrapper/assets/834921/d909a9b5-715d-4b74-9570-89901613129f)

But I couldn't find a way to change it. Is there one?

**Comment by awvalenti** [comment]
![Peek 13-06-2024 16-05](https://github.com/vrapper/vrapper/assets/834921/b5afb3be-a667-4023-9eb2-c9d6d5324457)
Ideally, I'd like it to use the search color (yellow in the example above). It's already being used for `incsearch`, but gets changed when the search is confirmed (with Enter).

**Comment by albertdev** [comment]
Hi, the XML you found does indeed contain the default color, but it is also a declaration to add things to the Preferences screen.

The setting can be found here:
![image](https://github.com/vrapper/vrapper/assets/1451362/627b25ff-65a5-405f-8e34-b504061de97d)

**Comment by awvalenti** [comment]
Awesome, thanks! I turned this into an SO Q&A: https://stackoverflow.com/questions/78623647/how-to-change-vrapper-colors/78623648
